export const balzac=[
 {id:1,
  mainImage:'/Images/1mainImage.webp',
  title:'Escapade Suisse à Neuchâtel ',
 image:[
  {image1:'/Images/1mail-poste1830.webp',description:"Malle-poste 1830"},
 {image2:'/Images/1diligenceLaffitteCailleud1825.webp',description:'Diligence Laffitte et Caillaud 1825'},
 {image3:'/Images/1ListeRelaisPosteDeFrance1782.webp',description:'Liste des relais de poste de France 1782'},
 {image4:'/Images/1HotelLeFauconNeuchatel.webp',description:'Hôtel Le faucon. Neuchâtel'},
 {image5:'/Images/1bancPierreNuchatel.webp',description:'Banc de pierre situé initialement sur la         "Promenade carrée de l\'Evole" à Neuchâtel, témoin du passage de Balzac et Mme Hanska'},
 {image6:'/Images/3AccidentVoyage19siecle.webp',description:'Accident de voyage 19ème siècle'},
  {image7:'/Images/3SchrannebplatzMunich1835.webp',description:'La Schrannenplatz à Munich 1835'},
  {image8:'/Images/3GuideDesEtrangers.webp',description:'Guide des étrangers'},
  {image9:'/Images/5photo.webp',description:'Pont'},
  
 

],
text:['C’est en septembre 1833 que Balzac entreprend le premier voyage pour rejoindre Mme Hanska, cette correspondante encore inconnue qu’il sait seulement être polonaise et se prénommer Eva et dont il est tombé follement amoureux au fil de leurs échanges épistolaires.Au début 1833, Madame Hanska avait convaincu son époux Mr Hanski de quitter leur domaine ukrainien pour un voyage d’agrément de plusieurs mois à travers l’Europe.',

' Elle avait alors proposé Neuchâtel comme lieu de villégiature, sa proximité avec la frontière française ne pouvant que favoriser une rencontre secrète avec Balzac.Si Balzac ne divulgue pas à son entourage la véritable raison de son voyage, par souci de ne pas  compromettre sa belle « Etrangère » et surtout de ne pas éveiller la jalousie de Madame de Berny, il s’en ouvre dans une lettre à sa sœur : « N’est-ce pas gentil d’avoir arraché un mari – qui m’a l’air d’une tour – de l’Ukraine, et de faire six cent lieues pour aller au devant d’un amant qui n’en fait que 150, le monstre ? ». Le dimanche 22 septembre 1833 au soir, prétendant à son entourage se rendre à Besançon pour y rencontrer un fournisseur de papier de qualité pour l’impression de ses œuvres, Balzac quitte Paris par la malle-poste pour un trajet d’environ 630 kms jusqu’à Neuchâtel.Voyager en France au temps de la poste aux chevaux est loin d’être une détente. Le voyage s’évalue à cette époque davantage en temps, celui du calendrier et de l’horloge, qu’en lieues ou kilomètres. Ainsi disait-on au 16ème siècle que la France tenait dans un losange de vingt-deux journées de large et dix-neuf de long...Le confort et la durée de tout déplacement à cheval dépendait pour le voyageur de ses capacités financières. Plusieurs possibilités s’offraient à lui : voyager par ses propres moyens en individuel, jouissant ainsi d’un plus grand confort et d’une liberté de choisir son itinéraire et son allure ; ou voyager en transport collectif, soit par Diligence, soit par Malle-poste.',

'On comprend que Balzac, toujours dans une course effrénée après le temps, ait opté pour ce dernier moyen de transport.En effet, la diligence, dont le service était gérée par des entreprises publiques, était une voiture monumentale, inconfortable et compartimentée, pouvant transporter jusqu’à 16 voyageurs. En outre, elle se déplaçait à plus faible allure afin de ne pas détériorer les chemins (une diligence pouvait atteindre 7 tonnes à pleine charge…). A partir de 1794, l’administration des postes crée un service de transport de voyageurs au moyen de ses propres véhicules utilisés pour acheminer le courrier. La malle-poste va alors fortement concurrencer le service des diligences car elle présente de nombreux avantages.La voiture est plus légère, traînée par quatre chevaux et ne propose au plus que quatre places pour les voyageurs. Elle est composée de trois compartiments : l’un destiné aux voyageurs, le second au courrier et le troisième aux paquets de lettres, journaux et dépêches. En outre, contrairement aux diligences, les malle-poste circulent au galop, de jour comme de nuit, et sont prioritaires sur les routes ainsi qu’aux relais à chevaux. ',

'Balzac s’engage ce 22 septembre à 6 heures du soir sur la route postale de Besançon, passant par Troyes et Dijon, selon un itinéraire précis jalonné par les relais de poste (répertoriés dans la liste générale des postes de France). L’allure moyenne d’une malle-poste en 1833 est de l’ordre de 10 km par heure (les chevaux parcourent environ 9 km en 50 mn) quand elle n’est pas diminuée par des intempéries, le mauvais état de la route, les défaillances des hommes ou des chevaux, des problèmes liés aux voitures ainsi que les actes de brigandage possibles.Un voyageur du 21ème siècle, habitué au confort, peut se faire une petite idée de la pénibilité d’un tel trajet grâce aux témoignages laissés par certains écrivains de l’époque. Ainsi, Victor Hugo, contemporain de Balzac, relate à un ami l’un de ses périples en malle-poste :',

'« […] j\'ai passé deux nuits en malle-poste, ce qui m\'a laissé une haute idée de la solidité de notre machine humaine. C\'est une horrible chose qu\'une nuit en malle-poste. Au moment du départ tout va bien, le postillon fait claquer son fouet, les grelots des chevaux babillent joyeusement, on se sent dans une situation étrange et douce, le mouvement de la voiture donne à l\'esprit de la gaîté et le crépuscule de la mélancolie. Peu à peu la nuit tombe, la conversation des voisins languit, on sent ses paupières s\'alourdir, les lanternes de la malle s\'allument, elle relaie, puis repart comme le vent ; il fait tout à fait nuit, on s\'endort. C\'est précisément ce moment-là que la route choisit pour devenir affreuse ; les bosses et les fondrières s\'enchevêtrent ; la malle se met à danser. Ce n\'est plus une route, c\'est une chaîne de montagnes avec ses lacs et ses crêtes, qui doit faire des horizons magnifiques aux fourmis. Alors deux mouvements contraires s\'emparent de la voiture et la secouent avec rage comme deux énormes mains qui l\'auraient empoignée en passant ; un mouvement d\'avant en arrière et d\'arrière en avant, et un mouvement de gauche à droite et de droite à gauche, - le tangage et le roulis. Il résulte de cette heureuse complication que toute secousse se multiplie par elle-même à la hauteur des essieux, et qu\'elle monte à la troisième puissance dans l\'intérieur de la voiture ; si bien qu\'un caillou gros comme le poing vous fait cogner huit fois de suite la tête au même endroit, comme s\'il s\'agissait d\'y enfoncer un clou. C\'est charmant. à dater de ce moment-là, on n\'est plus dans une voiture, on est dans un tourbillon. […] » Victor Hugo, Le Rhin, lettres à un ami, Lettre XXVIII',

'Balzac arrive à Besançon après 40 heures de voyage dans la matinée du 24 septembre, voyage ponctué par les arrêts successifs aux relais de poste pour y déposer le courrier et changer de monture. Après avoir rencontré un ami en ville, il reprend la route le soir même pour rejoindre Neuchâtel. En passant par Ornans, après avoir franchi le Doubs, il arrive enfin, épuisé, dans le canton de Neuchâtel par le Val de Travers. Il prend une chambre à l’hôtel Le Faucon qui était alors le plus élégant hôtel de Neuchâtel.',

'Le jour même de son arrivée, Balzac fait enfin la connaissance de madame Hanska en secret : il est pétri d’amour … Il passe les cinq jours suivants en compagnie de la comtesse et celle, qu’il déplore un peu trop systématique, de son époux Monsieur Hanski ! Profitant d’un bref moment d’absence de celui-ci, les amoureux réussissent à échanger « le furtif baiser premier de l’amour »… Le séjour à Neuchâtel se termine alors sur le projet de se retrouver plus tard à Genève. ',

'Balzac reprend la route pour Paris le 1er octobre 1833 dans des conditions de transport encore plus éprouvantes qu’à l’aller : il voyage vers la capitale durant quatre jours et quatre nuits, installé sur l’impériale d’une diligence, c’est-à-dire sur la banquette placée au dessus du coupé et qui n’était protégée du froid et de la pluie que par une capote de cuir ou de bois.',

'Il arrive à Paris le 4 octobre au soir. Dans une lettre à Mme Hanska, Balzac lui décrit la torture endurée : « Mon amour chéri, me voici, bien fatigué à Paris ; je suis au 6 8bre et il m’a été impossible de t’écrire auparavant. Il y avait un monde fou sur toute la route et par chaque ville où nous sommes passés, la voiture a refusé 10 à 15 voyageurs. La Malle-poste était retenue pour 6 jours, en sorte que mon ami de Besançon n’a pu m’y avoir une place ; j’ai donc fait la route sur l’impériale d’une diligence en compagnie de 5 Suisses du canton de Vaud qui m’ont traité corporellement comme un animal qu’on mène au marché et qui ont singulièrement aidé les paquets  à me contusionner. Je me suis mis au bain en arrivant [dans la soirée du 4 octobre] et j’ai trouvé ta chère lettre. » ',

'Coup de foudre ou consécration d’un amour déjà bien affirmé au fil des échanges épistolaires ? Ou bien les deux ? Balzac et la comtesse Hanska semblent déjà sous le joug de l’impatience amoureuse… Ils se séparent, au bout de ce court séjour, avec le projet de se retrouver très prochainement à Genève.La comtesse Hanska réussira-t-elle cependant à convaincre son époux de continuer leur périple en faisant une halte dans cette ville ? Ne va-t-elle pas au dernier moment réfréner son élan amoureux, par crainte de son mari ? Le baiser échangé si furtivement à Neuchâtel peut-il faire espérer d’avantage à Balzac ?'],
 },
 {id:2,
  mainImage:'/Images/2mainImage.webp',
  title:'Genève...Braises et flocons de neige ',
  image: [
    {image1:'/Images/2gravureLacLeman.webp', description:"Gravure du Lac Léman"},
  {image2:'/Images/2mallePosteDoleGeneve1832.webp',description:'Malle-poste de Dole à Genève 1832'},
  {image3:'/Images/3pageText.webp',description:'Text'},
  {image4:'/Images/4Berlin1840.webp',description:'Berlin vers 1840'},
  {image5:'/Images/5LeThéâtreRoyalBerlin1833.webp',description:'Le théâtre royal de Berlin 1833'},
  {image6:'/Images/4LaPostdamerBahnhof1843.webp',description:'La Postdamer Bahnhof,gare de départ à Berlin pour Postdam, 1843'},
  {image7:'/Images/4cheminsDeFer.webp',description:'chemin de fer'},
  {image8:'/Images/4Berlin1840.webp',description:'Berlin vers 1840 '},
  {image9:'/Images/5RomePhotoColisée1846.webp',description:'Rome : photo du Colisée datant de 1846'},
  

],
text:['Même si Balzac brûle d’impatience de rejoindre Madame Hanska à Genève afin d’y  consolider leur relation amoureuse prudemment amorcée à Neuchâtel, son travail littéraire et ses affaires vont le retenir à Paris plus longtemps que prévu. Pris par ses engagements contractuels auprès de divers éditeurs et par la nécessité de se constituer une « caisse » pour entreprendre le voyage, il redouble d’énergie à son travail d’écriture : « Donc maintenant il faut travailler jour et nuit.',

'  Quinze jours de bonheur à conquérir à Genève, voilà les paroles que je trouve gravées en dedans de mon front et qui m’ont donné le plus fier courage que j’aie jamais eu ». Le fruit de ce travail dense et passionné sera la parution, début décembre 1833, de son œuvre « Eugénie Grandet ». Elle est triomphalement accueillie. Fort de ce succès, Balzac quitte enfin Paris le cœur léger et le porte-monnaie plus fourni le 21 décembre 1833, emportant dans ses bagages le manuscrit d’Eugénie Grandet qu’il compte offrir à Mme Hanska. Il emprunte probablement les mêmes itinéraire et moyen de transport que pour se rendre à Neuchâtel, en passant par Troyes et Dijon et en continuant par Dole. Il arrive sur les bords du lac Léman le mardi 24 décembre et descend à l’auberge de l’Arc, non loin de la pension où réside la famille Hanski. ',

'Mme Hanska lui fait parvenir dès son arrivée un présent plein de promesses : l’un de ses cheveux noirs serti dans un anneau. Il ne quittera plus le doigt de Balzac… Balzac restera à Genève jusqu’au 8 février, partageant ses journées entre son travail d’écriture quotidien (il y consacre 12 heures d’affilées, de minuit à midi, plongé dans la rédaction de Séraphita), des mondanités et promenades en compagnie du couple Hanski au cours desquelles les deux amoureux intensifient leur relation. Au bout de quatre semaines de manœuvres patientes mais assidues auprès de Mme Hanska, Balzac concrétise enfin le but de son voyage à Genève : le dimanche 26 janvier, ils deviennent amants à l’hôtel de l’Arc…',

'Balzac quitte Genève le 8 février et arrive à Paris le 12 février. Le voyage de retour qui dure 4 jours, est extrêmement pénible par le temps d’hiver en montagne. Il écrit à Mme Hanska le lendemain de son retour : « Le froid a été vif. Le samedi matin, j’ai fait tout le Jura à pied, dans la neige […]. Aujourd’hui, je me replonge dans mes travaux, et ils sont écrasants »',

'A l\'issue de ce voyage suisse qui a vu naître leur idylle, les amants se sont promis d\'unir leur destin à jamais dans un avenir qui aura raison des obstacles de l\'espace et du temps qui les séparent.Vaine promesse ou espoir du domaine du possible ? Quand et où Balzac et l\'épouse Hanska pourront-ils entretenir la flamme à peine naissante mais déjà ardente ? Quel subterfuge Balzac pourra-t-il trouver pour justifier auprès du comte Hanski un nouveau séjour en leur compagnie ?...']
 },
 
 
 {id:3,
  mainImage:'/Images/3mainImage.webp',
  title:'Vienne...Roulez Calèche! ',
  image: [
    {image1:'/Images/3MaisonBalzacCassini.gif', description:'Maison de Balzac Rue Cassini'},
  {image2:'/Images/3calecheVoyage1830.webp',description:'Calèche de voyage 1830'},
  {image3:'/Images/3ChateauWeinheim1840.webp',description:'Le château de Weinheim aux environs de 1840'},
  {image4:'/Images/3stuttgart1835.webp',description:'Stuttgart 1835'},
  {image5:'/Images/3linz1840.webp',description:'Linz aux environs de 1840'},
  {image6:'/Images/3Schonbrubb1850.webp',description:'Schönbrunn 1850'},
  {image7:'/Images/3aubergeBirne1830.webp',description:'Auberge "Zur goldenen Birne" vers 1830'},
  {image8:'/Images/3salleBalLithographieVonBensa.webp',description:'Salle de bal de l\'auberge "Zur goldenen Birne"Lithographie d\' Alexander von Bensa'},
  {image9:'/Images/5BasiliqueSaint-Pierre1874.webp',description:'Basilique Saint-Pierre 1874'},
  
  
 
],
text:['Balzac, qui n’en est pourtant pas à sa première idylle, considère déjà la belle Madame Hanska comme la femme providentielle de sa vie, son « étoile polaire », ainsi qu’il la nomme, qui le guidera dans les méandres de son existence, qui lui apportera le réconfort auquel il aspire, tout à la fois dans le domaine affectif, financier et du prestige social… Dès son retour à Paris en ce mois de février 1834, enivré par sa nouvelle liaison amoureuse, il se remet à son travail d\'écriture avec ardeur. Il devine, en outre, que la séduction littéraire es un atout majeur auprès de la belle aristocrate... Ainsi, durant cette année 1834, Balzac produit avec une énergie quasi surhumaine un nombre impressionnant d’œuvres dont son chef d’œuvre Le Père Goriot.Cependant, c’est aussi avec une ardeur égale que Balzac reprend son rythme de dépenses parisiennes exorbitantes et qu’il engrange les dettes : achat d’un nouvel appartement rue Cassini, sorties mondaines, dépenses vestimentaires extravagantes…Seule l’écriture acharnée peut lui permettre de les résorber en partie et de se constituer une petite cagnotte pour rejoindre prochainement sa maîtresse.Les mois passent à Paris, pendant lesquels la famille Hanski poursuit son séjour en Italie : Venise, Florence, Naples. A la fin de l’été 1834, le couple retourne à Vienne pour y passer l’hiver et prévoit de repartir pour l’Ukraine au printemps 1835.',

'Le temps presse pour les amants s’ils veulent se revoir avant l’exil de la bien-aimée au fin fond de la campagne ukrainienne… Balzac, malgré son désir ardent de « baiser ce front idolâtré, sentir ces cheveux aimés », souhaite terminer son œuvre en cours Séraphîta avant de quitter Paris. Madame Hanska, quant à elle, réussit tant bien que mal à retarder son voyage de retour, au risque que cela semble suspect à son mari qui s’impatiente de rentrer sur ses terres. Le mois de mai sera le dernier délai pour une dernière rencontre…',

'Balzac n’a évidemment pas d’argent devant lui. Il s’en procure par des méthodes qui lui sont maintenant familières : vente d’objets au Mont-de-piété, demande d’avance de paiement aux éditeurs et aux journaux.Il prépare son voyage à la hâte et fixe son départ pour Vienne au 9 mai. Trouver un prétexte à fournir au mari Hanski ainsi qu’à son entourage n’est pas chose ardue pour Balzac qui déborde d’imagination… Il prétend, sans doute à juste raison d’ailleurs, que l’écriture de son roman La Bataille, projeté depuis des années, nécessite qu’il connaisse les villes de Wagram et Aspern. Celles-ci se situant tout près de Vienne, une petite visite au couple Hanski tombe sous le sens !',

'Balzac n’a aucune envie de revivre l’inconfort d’un voyage effectué en malle-poste. De plus, Vienne, ville impériale, mérite quelques égards… Le 7 mai, il loue chez le carrossier Panhard « une calèche poste chaise », pour un aller-retour Paris-Vienne. Le prix convenu s’élève à 400 francs de l’époque, ce qui équivaudrait très approximativement à 1 500 euros d’aujourd’hui. La calèche présente le précieux avantage d’être une voiture légère donc rapide, tractée par deux chevaux, ne transportant qu’un seul ou deux passagers, ce qui évite la promiscuité « écrasante» qu’a subie Balzac lors de son précédent voyage... Au frais de location de calèche viennent s’ajouter ceux, pas moins élevés, d’un serviteur en livrée (qui est pour l’occasion son valet de chambre Auguste) que Balzac s’attribue en grand seigneur pour le voyage. Le serviteur, qui voyage à l’arrière de la calèche, a pour fonction d’aider son maître à monter et descendre de la voiture, ce qui pouvait s’avérer d’un grand secours dans certaines situations…',

'Balzac quitte donc Paris le 9 mai, emportant dans ses bagages le manuscrit de Séraphîta qu’il compte terminer à Vienne. Il emprunte la route postale de Strasbourg, qui passe par Chalons et Metz. Après avoir traversé Strasbourg et Karlsruhe, il continue vers Heidelberg et fait escale au château de Weinheim, afin de rendre visite à Mme Jane Digby. Après cette halte d’une journée, Balzac reprend avec impatience la route qui traverse le sud de l’Allemagne, en passant tout d’abord par Stuttgart, puis Munich. Il atteint enfin les terres autrichiennes, passe par Linz et Schönbrunn, lieu de résidence de la famille impériale et arrive à destination le 16 mai à une heure de l’après-midi. En comprenant l\'escale à Weinheim, le voyage aura duré sept jours.',

'Dès son arrivée, Balzac descend à l’auberge « Zur goldenen Birne » (auberge de la Poire d’Or) située près du quartier du Prater, dans la Landstrasse, non loin de l’hôtel luxueux « Walterisches Haus » où séjourne le couple Hanski. L’établissement « Zur goldenen Birne » est à l’époque particulièrement prisé par la société viennoise pour ses bals organisés régulièrement, avec à la tête de l’orchestre de prestigieux musiciens tels que Johan Strauss père. Le hasard veut que Balzac, sans le savoir, y occupe la chambre même où Charles Thirion, amant français de la comtesse Luise Thürheim (elle-même amie de Madame Hanska), se suicida deux ans auparavant, un pistolet dans une main et le roman de Balzac La Peau de chagrin dans l’autre…',

'La renommée de Balzac a franchi les frontières françaises et c’est avec surprise et délectation que l’écrivain découvre la grande admiration que la société viennoise voue à son œuvre. Des membres de la plus haute aristocratie le prient à maintes reprises d’honorer leurs soirées de sa présence. Le chancelier même, le prince Metternich, l’invite chez lui pour un entretien. Balzac jubile… Cependant, si ce séjour comble son amour-propre au-delà de toute espérance, il semble peu propice à l’épanouissement de sa liaison avec la belle Polonaise… Leurs rencontres se bornent pour l’essentiel à des soirées mondaines dans le cercle d’amis du couple Hanski, qui excluent tout moment d’intimité. Peut-être que Madame Hanska, sachant que tout Vienne a les yeux rivés sur Balzac, préfère rester prudente. Peut-être aussi que Monsieur Hanski commence à trouver l’amitié de Balzac, au nom de laquelle il n’hésite pas à parcourir plus de 1 000 kms, quelque peu excessive pour être sans arrière-pensée…',

'Balzac se sent frustré. D’autant plus que ces obligations mondaines répétées mettent à mal non seulement sa discipline de travail mais aussi ses économies. Très vite à court d’argent, Balzac se fait payer à la Banque Rothschild au nom de son éditeur Edmond Werdet, une avance de 1 500 francs sur son œuvre en cours Le Lys dans la vallée, c’est-à-dire plus de 5 000 euros actuels. Le 31 mai, Balzac visite en compagnie du général-prince Schwarzenberg  le champ de bataille de Wagram qui constituait le but officiel de son voyage en Autriche. Il décide de quitter Vienne le jeudi 4 juin, n’ayant plus le sou et convaincu qu’il n’aura aucune occasion d’enlacer son amante : « Mon Ève adorée, je n\'ai jamais été si heureux, je n\'ai jamais tant souffert. Un cœur plus ardent que l\'imagination n\'est vive est un funeste présent, quand le bonheur complet n\'étanche pas la soif de tous les jours. Je savais tout ce que je venais chercher de douleurs, et je les ai trouvées.[…] Allons, mille baisers, car j\'en ai une soif que ces petites surprises ne font qu\'accroître. Nous n\'aurons ni une heure, ni une minute. Ces obstacles attisent une telle ardeur que je fais bien, crois-moi, de hâter mon départ. »',

'Balzac reprend donc la route pour Paris en empruntant le même parcours qu’à l’aller. Après quarante-huit heures de voyage, il fait une halte imprévue à Munich, après avoir eu un accident non loin de là, à Hohenlinden. Il raconte ses mésaventures à Mme Hanska dans une lettre  datant du 7 juin : « Je suis arrivé hier à Munich, il était onze heures du soir, mais j\'y serais venu en trente-six heures au lieu de quarante-huit, sans trois mauvais postillons, qu\'aucune puissance humaine n\'a su faire aller et qui, chacun, m\'ont perdu trois heures. J\'ai dormi sept heures et, je viens de me réveiller pour m\'acquitter de la promesse que je vous ai faite de vous écrire un mot. Puis, à dix heures, après avoir vu l\'extérieur des édifices, je repartirai avec la même célérité.',

'Je n\'ai rien de romantique à vous mander sur un voyage, toujours triste quand on quitte de bons amis. Je n\'ai eu d\'autres événements que deux chevaux qui avaient l\'habitude d\'aller chercher du sable et qui ont failli me jeter dans la carrière, le postillon n\'ayant pas pu les empêcher d\'aller à leurs habitudes. Je me suis jeté à temps hors de la voiture et j\'ai fait comme eux, j\'ai repris le chemin de Vienne ; mais on leur a prouvé à coups de fouet qu\'il fallait aller à Hohenlinden, et la nécessité aussi m\'a prouvé qu\'il faut retourner à Paris. Le postillon craignait que je ne le grondasse. Mais il ne savait pas que les chevaux et moi nous étions également fidèles à nos habitudes, malgré le devoir. J\'ai fait mille tristes réflexions sur la manière dont les chevaux et les hommes perdent leur liberté, sur les divers freins qu\'on leur met, sur les coups du sort et les coups de fouet […] »',

'Balzac profite donc de cet arrêt forcé pour visiter la ville bavaroise. Peut-être se procure-t-il l’un des premiers guides de voyage, rédigé par Adolphe de Shaden et imprimé la même année 1835, pour s’orienter dans la ville qui compte déjà à l’époque environ 3 350 maisons et seize grandes places publiques… Munich, en tout cas, ne ravit pas notre voyageur : est-il dans de mauvaises dispositions pour apprécier la ville, est-il rebuté par le nombre d’interdits qui y semblent en vigueur, si l’on en croit le guide ? Son verdict est sévère et sans appel : « Je ne suis pas content de Munich. C\'est par trop de fresques et par trop de mauvaises fresques. Celles du haut plafond de la Pinacothèque valent seules quelque chose, et celles des salles d\'en bas de la Kœnigsbau.  Tout le reste est à la hauteur de nos décorations de cafés, à Paris ».',

'Balzac reprend la route après 2 jours de halte à Munich et arrive sans autre encombre à Paris le 11 juin dans la nuit. Il écrit le jour même à Madame Hanska : « Je suis arrivé le 11 à deux heures du matin. Ainsi, en déduisant le temps de mon séjour à Munich, j\'ai fait la route en cinq jours. Mais je suis sûr maintenant qu\'elle peut se faire en quatre, et qu\'on peut aller en onze jours à Wierzchownia. Je suis arrivé horriblement fatigué, brun comme un nègre et je n\'ai pu que me jeter sur un lit et dormir. Je vous écris ce soir selon ma promesse […]. » Alors que Balzac se replonge avec une énergie redoublée dans son travail d’écriture, pour rattraper le retard accumulé à Vienne et pour éponger les dettes de voyage, la famille Hanski s’apprête à rejoindre son domaine en Ukraine… Balzac sait que le temps des petites escapades pour retrouver sa maîtresse est révolu et son désir de lui être uni à jamais en est d’autant plus renforcé : « Rien ne peut me détacher de toi ; tu es ma vie et mon bonheur, toutes mes espérances. Je ne crois à la vie qu\'avec toi. Que peux-tu craindre ? Mes travaux te prouvent mon amour, et ça a été préférer le présent à l\'avenir que de venir ici. C\'est la bêtise de l\'amour ivre, car j\'ai reculé, pour jouir de ce moment, de plusieurs mois les jours où tu crois que nous serons libres, plus libres, car libres, oh je n\'ose pas penser à cela. Il faut que Dieu le veuille ! Je t\'aime tant et tout nous unit si bien que cela sera ; mais quand ? » ----------- Les amants sont confiants et optimistes quant à leur réunion prochaine et définitive : l’époux Hanski a à présent cinquante-trois ans et sa santé semble fragile… Qu’en sera-t-il ? Balzac ira-t-il rejoindre pour toujours son amour à Wierzchownia dans un avenir très proche ?',
]
 },
 {id:4,
  mainImage:'/Images/4mainImage.webp',
  title:'Saint-Pétersbourg...à toute vapeur !',
  image: [
  {image1:'/Images/4LeBritannia1842.webp',description:'Le Britannia 1842'},
  {image2:'/Images/4IntérieurPaquebotDevonshire.webp',description:'Intérieur d\'un paquebot du type Devonshire'},
  {image3:'/Images/4PaquebotPleineMer1840.webp',description:'Paquebot en pleine mer vers 1840'},
  {image4:'/Images/4LaPerspectiveNevski1850.webp',description:'La Perspective Nevski 1850'},
  {image5:'/Images/4DePartFleuve.webp',description:'De part et d\'autre du fleuve :la tour de la forteresse Hermann de Narva et la forteresse russe d\'Ivangorod'},
  {image6:'/Images/4ErmitagePontErmitage1826.webp',description:'Ermitage et pont de l\'Ermitage 1826'},
  
  {image7:'/Images/4JournalRouen.webp', description:'Journal de Rouen'},
  {image8:'/Images/4CampKrasnoïeSelo1840.webp',description:'Camp de Krasnoïe Selo 1840'},
  {image9:'/Images/5Anvers1880.webp',description:'Anvers vers 1880'},
  
 
  
],
text:['Le séjour viennois a endetté Balzac de façon impériale… La majeure partie de l’argent englouti aussi vite dans ses folies de grandeur avait été obtenue selon son système habituel, en se faisant payer ses futurs ouvrages (parfois même pas encore commencés) par les journaux et éditeurs contre un engagement de livraison à une date fixée. Pris dans le tourbillon viennois, il n’a cette fois-ci pas suffisamment travaillé pour honorer ses engagements littéraires et son retour à Paris le plonge de suite dans une période de labeur acharné et de conflits juridiques avec l’éditeur François Buloz à qui il devait la livraison du roman Le Lys dans la vallée. Balzac est conscient que la masse de travail à fournir, proportionnelle aux dettes à résorber, ne peut lui faire espérer de rendre visite au couple Hanski en Ukraine dans les mois à venir… En cette année 1835, il s’installe de nouveau dans son rythme parisien : travail littéraire assidu – quelques soirées mondaines et aventures amoureuses – nombreuses dépenses extravagantes et spéculations vouées immanquablement à l’échec – dettes aggravées – travail littéraire forcené. Les années passent, durant lesquelles Balzac enrichit son édifice littéraire d’innombrables chefs-d’œuvre et au fil desquelles l’espoir de rejoindre l’étoile polaire ne devient qu’une faible lueur. Leur correspondance s’est en effet peu à peu distendue au fil de ces années, teintée souvent de reproches réciproques et d’amertume. Madame Hanska, tenue au courant des « incartades» de Balzac par l’intermédiaire de la communauté polonaise installée à Paris, reproche souvent à son homme d’avoir brisé les chaines de la fidélité qu’ils s’étaient promise à Genève, ce que dément catégoriquement Balzac, souvent avec mauvaise foi et agacement … C’est dans ce contexte que Balzac reçoit, le 5 janvier 1842, la lettre lui annonçant le décès de Monsieur Hanski le 10 novembre 1841. Enfin le jour tant attendu, devenu inespéré pour Balzac âgé maintenant de quarante-trois ans, est arrivé ! Sa fougue amoureuse renaît alors de ses cendres à la vitesse de l’éclair…',

'Il fait part à la jeune veuve de son intention de la rejoindre immédiatement à Dresde où elle séjourne depuis quelques temps. Celle-ci s’y oppose formellement, Balzac en est littéralement mortifié. Ce refus se justifie sans doute par les problèmes d’héritage auxquels elle est confrontée : l’un des parents de Monsieur Hanski a en effet engagé une action judiciaire contestant le testament de celui-ci et remettant en cause la communauté de biens avec son épouse. Madame Hanska a perdu le procès tenu à Kiev et doit faire appel à Saint-Pétersbourg pour tenter d’entrer en possession de ses droits.  Balzac ronge son frein – d’autant que l’issue du procès concernant la fortune de sa maîtresse ne lui est pas indifférente… – jusqu’à ce que Madame Hanska lui donne enfin,  en avril 1843, la permission de la rejoindre à Saint-Pétersbourg. Balzac se lance alors dans une course surhumaine mettant en péril sa santé, pour terminer les deux romans qui constitueront sa cagnotte de voyage : Splendeurs et Misères des courtisanes et David Séchard (3ème partie des Illusions perdues). Il pense pouvoir se rendre en Russie fin juillet. Exténué, il avoue à Madame Hanska : « Ma fatigue dépasse tout ce que vous pouvez imaginer, je suis un corps presque mort, mais un corps voyageur. »',

'Il engage immédiatement les démarches administratives requises pour l’entrée en Russie. Les formalités que doit remplir tout Français souhaitant s’y rendre en 1843 sont plus longues et compliquées que de nos jours…  Le futur voyageur doit commencer par faire remplir par sa mairie une demande de passeport, appuyée par des certificats des autorités locales : pièces d’état civil, certificat de domicile et certificat de bonne vie et mœurs. Le passeport, établi par le préfet sur l’appui de ces documents, est ensuite envoyé au Ministère de l’intérieur qui le soumet lui-même au visa de l’Ambassade de Russie, par l’intermédiaire des Affaires étrangères. Le 14 juillet 1843, après une longue attente, Balzac vient enfin retirer son passeport visé auprès du secrétaire de l’ambassade, Victor Balabine. Celui-ci dresse un portrait de l’illustre écrivain pour le moins peu flatteur … : « Un petit homme gros, gras, figure de panetier, tournure de savetier, envergure de tonnelier, allure de bonnetier, mine de cabaretier, et voilà. Il n’a pas le sou donc il va en Russie : il va en Russie, donc il n’a pas le sou. » Jusqu’alors, le voyageur français se rend en Russie soit par voie terrestre, en passant par Berlin ou bien par la Hollande, soit en partie par mer, en rejoignant Lübeck (Allemagne du Nord) par la route puis en traversant la mer Baltique jusqu’à Saint-Pétersbourg. L’apparition des bateaux à vapeur dans les années 1820 et surtout la création de compagnies maritimes assurant le trajet de voyageurs changent la donne…',

'En 1838, la compagnie maritime L’Europe obtient du tsar Nicolas 1er  le privilège d’exploiter une ligne régulière entre Le Havre et Saint-Pétersbourg par bateaux à vapeur. La concurrence est lancée et s’avère âpre dès le début : le 12 février 1840, ainsi que l’annonce Le journal de Rouen daté du 14 février, une nouvelle ligne Dunkerque – Saint-Pétersbourg est créée. La nouvelle compagnie insiste sur l’avantage de partir de Dunkerque, évitant ainsi « le passage périlleux de la Manche et du Pas de Calais » et se targue d’établir « ses prix de transport sans s’inquiéter des tarifs et surtout des menaces d’en cas de concurrence de Monsieur le directeur de la compagnie l’Europe ». Le duel engagé entre les deux compagnies sur le terrain des tarifs, durée de voyage et nombre de voyageurs embarqués durera jusqu’à leur fusion en 1844… En juillet 1843, Balzac opte d’emblée pour la compagnie de Dunkerque. D’autant plus que son directeur M. Châteauneuf, étant un grand ami de Léon Gozlan, lui-même très lié avec Balzac, lui promet de le « combler d’attentions, et de lui donner la meilleure cabine sur le pont » La traversée pour Saint-Pétersbourg est fixée au 21 juillet, pour une durée estimée de sept jours, à bord du paquebot Devonshire, nouvellement mis en ligne en remplacement du Britannia, avec service français et anglais auprès des passagers. Les tarifs en vigueur cette année-là sont de 200 frs pour la 1ère classe et de 150 frs pour la 2ème classe, soit respectivement environ 800 € et 600 € pour un aller-retour. Le 19 juillet 1843, sept ans après son dernier séjour auprès de Madame Hanska, Balzac quitte Paris avec la ferveur d’un jeune amoureux… : « Je pourrai peut-être, en deux mois, vous tant regarder, que je reprendrai mes sept ans de privation. Sept ans ! et tout ce que j’ai souffert. Eh ! bien, tout cela disparaîtra dans une minute. »',

'Le réseau de chemin de fer, encore à ses débuts, n’allant pas jusqu’à Dunkerque, il rejoint le port d’embarcation par malle-poste, en empruntant l’actuelle route nationale 16 qui passe par Pierrefitte-sur-Seine, Amiens et Hazebrouck. Le paquebot Devonshire l’attend à quai dans le port de Dunkerque. En cette année 1843, nous sommes encore bien loin de l’ère des croisières de rêve… Il faut attendre le développement des traversées transatlantiques à la fin du 19ème siècle pour voir apparaître des paquebots de plus en plus imposants et sophistiqués. Le Devonshire, tout comme le Britannia, sont représentatifs des premiers bateaux à vapeur : bateaux mixtes à voiles, ils étaient propulsés par des roues à aubes fixées sur chaque flanc, actionnées par un moteur à charbon. Ils utilisaient cependant leurs voiles le plus possible car le combustible était cher et encombrant. D’une longueur d’environ 45 mètres et d’une largeur de 8 mètres, ces paquebots se déplaçaient à la vitesse moyenne de 7 nœuds, soit 13 km / h. En plus de leur cargaison, ils pouvaient embarquer une vingtaine de passagers. Le témoignage que livre Charles Dickens sur sa traversée de l’Atlantique à bord du Britannia en 1842 nous donne un aperçu des conditions de voyage qu’a dû endurer Balzac à bord du Devonshire, même en ayant bénéficié, comme promis, de la meilleure cabine du navire : absence de ventilation et de système de chauffage ;  pas d’eau courante ni de toilettes ;  pas de moyen de conservation de la nourriture, une fois fondue la glace dans laquelle on l’entrepose…Seule une vache attachée dans un renfoncement du pont fournit quotidiennement aux passagers une boisson à peu près saine. Le grand salon fait office en même temps de séjour et de salle à manger. Les repas y sont descendus de la cambuse située sur le pont, ce qui fait que par mauvais temps, la nourriture arrive froide dans les assiettes, bien souvent copieusement arrosée d’eau salée… Quant à la cabine, Dickens avoue ironiquement qu’elle « est si minuscule qu’essayer d’y caser les malles est aussi vain que de vouloir loger une girafe dans un pot de fleur » ! Balzac navigue malheureusement sur une mer agitée huit jours durant et arrive à Saint-Pétersbourg avec un jour de retard par rapport à la date prévue, soit le 29 juillet 1843.',

'Dès l’approche de Saint-Pétersbourg, la surveillance douanière du régime autocratique est extrêmement stricte envers les voyageurs européens. La compagnie maritime française rappelle d’ailleurs avant le départ de Dunkerque qu’il est interdit de confier aux marins toute lettre, paquet, journal ou autre objet. Une première inspection du paquebot est effectuée par la police douanière russe à Cronstadt, ville située sur l’île de Kotline, à une vingtaine de kilomètres de Saint-Pétersbourg. Les passagers doivent alors débarquer du navire de haute mer pour gagner Saint-Pétersbourg à bord d’un petit bateau à vapeur qui, selon Custine, est « sale et mal construit ». Les voyageurs peuvent y emmener les objets légers et les malles, à la condition toutefois qu’ils aient été auparavant scellés au plomb par les douaniers de Cronstadt, les voitures et bagages plus volumineux restant provisoirement sur l’île. La dernière épreuve attend les passagers occidentaux à hauteur du quai Anglais, en face de la douane urbaine de Saint-Pétersbourg. Il n’est pas rare que quelque passager français soit refoulé sans pouvoir descendre en ville, faute de ne pas satisfaire aux règlements douaniers en vigueur… Si Balzac souhaite séjourner incognito dans la capitale russe, c’est sans compter avec la presse pétersbourgeoise qui divulgue immédiatement son arrivée ainsi que le motif de son voyage : le Bulletin pour les gens du monde annonce l’arrivée d’un « certain français, au nom de famille compliqué, accompagné d’un titre : homme de lettre ». L’Abeille du Nord, mieux au fait de la renommée de Balzac, déclare qu’il serait venu à Saint-Pétersbourg « non pour ses activités littéraires, mais pour rendre visite à sa fiancée ». Cette révélation sécurise plutôt la haute société pétersbourgeoise, qui redoutait que l’écrivain ne soit venu avec les mêmes intentions que Mr de Custine : suite à un séjour en Russie en 1839, celui-ci formula une critique virulente du système autocratique russe dans son ouvrage La Russie de 1839.',

'Soucieuse de garder malgré tout une certaine discrétion sur la présence de Balzac à ses côtés, Madame Hanska lui a réservé un meublé à la Maison Pétroff, située tout près de la Maison Koutaïsoff, sa résidence de la rue Bolchaïa Millionaïa. Cette pension, tenue par Madame Tardif, une veuve francophone, est loin d’offrir le même standing que le prestigieux hôtel Demouth où elle avait initialement pensé loger Balzac. La chambre s’avère inconfortable et le lit est infesté de punaises, ce qui n’empêche pas Balzac de s’effondrer de fatigue : « Malgré les soins de la mère du grand homme, il y a des insectes ; mais j’ai dormi par la force de la fatigue, et j’ai maintes fois été réveillé par une affreuse migraine. J’ai été trop secoué hier, à part le cœur. Quoique fort, il y a des émotions qui dépassent mes forces.» Toujours est-il que la maison Tardif semble, avec le séjour de Balzac, destinée dès lors à accueillir des compatriotes français : en effet, ayant été endommagée pendant la seconde guerre mondiale, elle sera complètement transformée pour donner naissance à deux bâtiments, dont l’un abrite aujourd’hui le consulat de France… Le lendemain de son arrivée, à peine remis de son voyage éprouvant, Balzac se précipite avec une émotion intense chez la comtesse Hanska.Le « feuilleton » amoureux semble reprendre exactement là où il s’était interrompu sept ans auparavant, faisant fi des années qui ont transformé les deux p rotagonistes : « […] j’ai eu le bonheur, à midi environ, de revoir et de saluer ma chère comtesse Eve dans sa maison Kutaïsoff, grande Millione. Je ne l’avais pas vue depuis Vienne, et je l’ai trouvée aussi belle, aussi jeune qu’alors. Il y avait sept ans d’intervalle, cependant, et elle était restée dans ses déserts de blé comme moi dans le vaste désert d’hommes de Paris.[…] De 1833 à 1843, il s’est écoulé dix années, pendant lesquelles tous les sentiments que je lui porte ont, contrairement à la loi commune, grandi, de tous les chagrins de l’absence, et de toutes les déceptions que j’ai eues. On ne refait ni le temps ni les affections ! » Balzac et la comtesse Hanska, tout au long des six semaines suivantes, savourent enfin sans entrave leur amour, restant bien à l’abri de la société pétersbourgeoise … Après-midi passés dans le salon bleu de la comtesse, flâneries en amoureux le long des quais de la Néva, du Palais d’Hiver et de l’Ermitage, séances de « shopping » au grand Magasin Anglais situé à l’angle de la Perspective Nevski. Bref, une simple et douce vie de couple dont en avait rêvé Balzac depuis si longtemps…',

'Si la comtesse décline prudemment la plupart des invitations venant d’admirateurs de Balzac, qui sont nombreux à Saint-Pétersbourg, elle accepte cependant celle de son amie Hélène Smirnova. Fin août, le couple part lui rendre visite à Peterhof situé à 32 km à l’ouest de Saint-Pétersbourg, sur la baie de Kronstadt. Balzac en profite pour y découvrir le château construit pour Pierre Le Grand en 1726. Le 21 août, Balzac est invité, par l’entremise d’un Général allié à la famille de Mme Hanska, à la grande revue annuelle des troupes par le tsar Nicolas Ier, qui se déroule au camp de Krasnoïe Selo, à une vingtaine de kilomètres au sud de Saint-Pétersbourg. Y assistant sous un soleil de plomb, Balzac doit cependant se contenter de voir l’empereur à une distance de cinq mètres, sans pouvoir l’approcher d’avantage et encore moins lui adresser la parole. Il ne travaille pratiquement pas durant son séjour, totalement immergé dans son rêve d’amour…Sur son nuage, tous les lieux arpentés en compagnie de la comtesse lui semblent merveilleux. Ceci ne l’empêchera pas de porter un jugement assez critique sur la ville, une fois de nouveau installé dans sa vie parisienne. Il livre en 1845, dans son ouvrage Histoire et Physiologie des boulevards de Paris, une description peu engageante de la plus grande artère de Saint-Pétersbourg et d’une manière plus générale, de l’atmosphère qui règne dans la ville sous le régime autocratique du tsar : « La Perspective [Nevski] ne ressemble à nos Boulevards que comme le strass ressemble au diamant, il y manque ce vivifiant soleil de l\'âme, la liberté... de se moquer de tout qui distingue les flâneurs parisiens. Les usages du pays empêchent d\'y causer trois ou de s\'attrouper à la moindre cheminée qui fume trop. Enfin le soir, si beau, si agaçant à Paris, fait faillite à la Perspective ; mais les édifices y sont étranges, et si l\'Art ne doit pas se préoccuper de la matière employée, un écrivain impartial avouera que la décoration architecturale peut en certains endroits disputer la palme aux Boulevards. Mais toujours des uniformes, des plumes de coq et des manteaux ! mais pas un groupe où se fasse le petit journal ! mais rien d\'imprévu, ni filles de joie, ni joie. Les guenilles du peuple y sont sans variété. Le peuple, c\'est toujours la même peau de mouton qui marche ! »',

'Et de conclure… : « Oh ! À Paris, là est la liberté de l\'intelligence, là est la vie ! Une vie étrange et féconde, une vie communicative, une vie chaude, une vie de lézard et une vie de soleil, une vie artiste et une vie amusante, une vie à contrastes. » Balzac quitte Saint-Pétersbourg le 7 octobre 1843. Peu désireux de revivre l’épreuve de la traversée en mer, il décide de revenir à Paris par voie terrestre. C’est ainsi qu’il s’engage sur les routes traversant les provinces baltes de l’empire russe, à bord de la Karèta postoraya (malle-poste russe), avec pour compagnons de voyage deux jeunes sculpteurs russes se rendant à Rome, Nicolas Alexandrovitch Ramazanoff et K.M. Klimtchenko. Les voyageurs passent par Narva et Tartu en Estonie. Ils continuent par Riga et Mitau (aujourd’hui Ielgava) en Lettonie et atteignent enfin la frontière russo-prussienne à Tauroggen (aujourd’hui Taurage) en Lituanie, au bout de 3 jours et demi de route. Comme à chaque fois qu’il quitte la comtesse pour retourner à sa vie laborieuse de Paris, Balzac affiche une humeur maussade tout au long du trajet. Tout est sujet à critique. Cela commence par l’état des routes qu’il juge déplorable, sans doute d’ailleurs à juste raison : « […] la chaussée de Pétersbourg à Tilsitt n’existe que sur deux parties, de Pétersbourg à Narva, et de Riga à Tauroggen, moins deux stations, en sorte que sur environ une moitié, le chemin est détestable quand il a plu, et il avait beaucoup plu. Figurez-vous les soubresauts que nous faisions ; mais les voitures sont excellentes, car elles y résistent. Tout ce qui est russe a la vie très dure. […] » Cela continue par les plats locaux servis dans les relais qui indignent le gastronome français et lui font littéralement crier famine. Seule la dégustation du vin français qu’il a amené avec lui – du Sauternes et du Château-Margaux – et qu’il partage avec ses compagnons de route semble le sauver du marasme culinaire…  Les paysages et les villes baltes ne sont guère plus attrayants à ses yeux. Le sculpteur Ramazanoff, qui comprend et parle un peu le français, raconte avec ironie l’attitude de l’écrivain à son arrivée à Taurage : « Il était drôle de voir Balzac, enveloppé dans sa pelisse, chaussé d’énormes bottes fourrées, coiffé d’un bonnet de fourrure, ayant les mains dans un manchon de femme, pataugeant dans la boue et grognant : - En voilà une ville ! »',

'Après une halte d’une nuit à Tilsitt en Prusse orientale, les voyageurs poursuivent leur route, à travers les contrées prussiennes, à bord de la Schnell-post (malle-poste allemande). Ils arrivent à Berlin le 14 octobre à 6 heures du matin. Balzac descend à l’hôtel de Russie qui se situe à proximité des monuments touristiques de la ville. Après un repos bien mérité dans « le premier lit qui ressemble à un lit, depuis qu’ [il a] quitté Dunkerque », il part en compagnie de Ramazanoff arpenter la ville. La visite complète des monuments est bouclée en une heure ! On peut imaginer le degré d’enthousiasme de Balzac pour l’architecture berlinoise… Il semble avoir été plus attentif à l’atmosphère sociale de la ville prussienne. Il décrit ainsi ses impressions à la comtesse Hanska : « Berlin n’est pas comparable à Pétersbourg. […] Le prussien y foisonne, tandis que chez vous les habitants sont sans doute perdus dans les steppes des places et des perspectives. Les magasins, les figures, les passants, tout a un air indéfinissable qui ne s’explique pas encore par le mot liberté, mais qui se traduit par mœurs libres, ou mieux, liberté dans les mœurs. » Son jugement définitif de la ville n’en reste pas moins, encore une fois, sans appel puisqu’il annonce que « Berlin est la ville de l’ennui ; [qu’il] y mourrait en une semaine »… Le 16 octobre, il part rendre visite pour la journée au dramaturge allemand Ludwig Thieck à Potsdam ; il prévoit une excursion à l\'ancien palais d\'été du roi de Prusse Frédéric II, le palais de Sans souci. Suivant les indications de son ami naturaliste Alexandre de Humboldt, il emprunte le train à vapeur pour parcourir la distance de 70 km qui séparent les deux villes. Inaugurée en 1838, la section Berlin-Potsdam est la première ligne de chemin de fer construite en Prusse.',

'Dès le lendemain, Balzac décide de reprendre le chemin de retour vers Paris. Le réseau ferroviaire allemand est, en 1843, encore très fragmentaire et il oblige d’alterner train et Schnell-post. Ainsi, Balzac se doit d’étudier les itinéraires par souci d’efficacité et d’économie. La meilleure feuille de route semble de rejoindre Leipzig par train au départ de Berlin, pour continuer vers Mayence en Schnell-post, puis de poursuivre vers Paris, en partie en bateau à vapeur sur le Rhin et en train.Balzac arrive à Leipzig le 18 octobre, après un voyage d’environ 200 kms en train, accompagné du fidèle Ramazanoff. Son opinion sur le service ferroviaire allemand n’est pas, comme tout le reste, très élogieuse et Balzac ne peut s’empêcher de clamer la supériorité française : « Les chemins de fer allemands sont un prétexte pour boire et manger. On s’y arrête à tout moment, on descend, on mange, on boit et l’on y remonte, en sorte que la poste de France va aussi vite que ces rails-là. »… Il faut reconnaître que la critique n’est pas exagérée, si l’on en croit ce qu’en dit Edmond Teisserenc dans son rapport sur les chemins de fer, datant de 1842 : il y dénonce la durée interminable des stations, ce qui ramène la vitesse effective des trains allemands qui est d’environ 40 km/heure, à une vitesse moyenne de 25 kms/h… Balzac passe la nuit dans une chambre bon marché mais médiocre à l’hôtel "Stadt Rom" et entreprend de visiter Dresde pendant une journée, avant de continuer son voyage de retour. La foire qui se déroule à Leipzig au même moment vient perturber ses projets : toutes les places de la Schnell-post sont déjà réservées jusqu’au 22 octobre. Il décide alors de profiter de ce contretemps pour flâner tranquillement à Dresde qu’il rejoint en train. Dresde, enfin, bénéficie d’un traitement de faveur : la ville séduit Balzac ; il s’y sent bien, plus libre. Dès le lendemain de son arrivée, il transmet ses impressions à la comtesse Hanska : « J’ai fait tout Dresde, et c’est, je vous jure, une charmante ville, bien préférable, comme séjour, à Berlin. Elle tient de la capitale, de la ville suisse et de la ville allemande, les environs sont pittoresques, et tout y est charmant. J’ai conçu qu’on pût vivre à Dresde. Il y a un mélange de jardins et d’habitations qui recrée l’œil. » Il est conquis par l’architecture de la ville : il admire le palais et considère « qu’il n’y a rien en Russie, ni à Berlin, ni dans tout le nord qui vaille cela » ; il apprécie le théâtre « qui est bien le plus charmant théâtre [qu’il ait] vu », en précisant cependant que « c’est Desplechin, Séchan et Diéterle, les 3 décorateurs de notre Opéra français, qui sont venus l’arranger. »…',

'Ce que Balzac ne raconte pas à la comtesse, ce sont les maux de tête violents qui ne le laissent plus en paix depuis Berlin. Ces douleurs intenses s’avèreront être causées par une méningite qui deviendra chronique par la suite, et qui aurait été déclenchée par une insolation attrapée lors de la revue des troupes à Saint-Pétersbourg. L’écrivain commence à payer gravement les excès qu’il inflige à son corps et son esprit depuis de trop longues années… Le 22 octobre, il reprend la route pour Paris à bord de la Schnell-post. Il arrive dans la capitale parisienne vraisemblablement le 3 novembre au soir. Sur cette dernière partie du voyage, Balzac reste relativement laconique. Il semble qu’il ait suivi le chemin des écoliers pour effectuer le dernier tronçon de voyage en 10 jours…Les quelques informations transmises à la comtesse Hanska sur l’itinéraire exact emprunté, sont souvent confuses, contradictoires. Cette imprécision  peut être mise sur le compte de son état de santé, qui est réellement préoccupant. Mais elle peut aussi être feinte : il n’est en effet pas exclu que Balzac soit parti rejoindre Madame de Brugnol, sa gouvernante et maîtresse depuis 1840, pour un petit périple le long du Rhin puis en Belgique… A peine de retour à Paris, Balzac reprend la route le 8 novembre pour Le Havre, afin de récupérer ses malles qui elles, ont voyagé par bateau à vapeur depuis Saint-Pétersbourg. Il aura été absent de la capitale trois mois et demi en tout et ce n’est, encore une fois, que labeur littéraire et factures impayées qui l’accueillent à son retour. Le rythme à reprendre est d’autant plus pénible que son état de santé l’affaiblit considérablement. Le séjour à Saint-Pétersbourg, même s’il a permis à Balzac de donner enfin libre cours à sa passion amoureuse, ne l’a cependant pas totalement sécurisé quant à son avenir avec la comtesse Hanska. Il désire, de tout son être, l’épouser et mener enfin une vie sereine, tant sur le plan amoureux que sur celui de la sécurité financière. Plus rien ne s’y oppose, croit-il : la comtesse est libre et elle a obtenu à Saint-Pétersbourg gain de cause, concernant l’héritage de son époux défunt. Cependant, Eve Hanska ne semble pas partager cette impatience. Elle ne veut envisager leur propre mariage que lorsque sa fille Anna aura elle-même trouver un époux. Balzac doit donc avec résignation s’installer une fois de plus dans l’attente… Les éternelles interrogations le taraudent : Quand reverra-t-il la comtesse qui va bientôt s’exiler sur ses terres ukrainiennes ? Une fois sa fille mariée, consentira-t-elle à l’épouser ? Combien de temps, d’années peut-être devra-t-il attendre le mariage d’Anna ?...'
]
 },
 {id:5,
  mainImage:'/Images/5mainImage.webp',
  title:'Le tour d’Europe en 260 jours de récréation…',
  image: [
    {image1:'/Images/5journalCheminFer1.webp', description:"Chemin de fer 1page"},
  {image2:'/Images/5journalCheminFer2.webp',description:'Chemin de fer 2page'},
  {image3:'/Images/5Dresde1845.webp',description:'Dresde 1845. Se faisant face, l’hôtel Stadt Rom sur la droite de l’illustration, et l’hôtel de Saxe sur la gauche.  '},
  {image4:'/Images/5ThéâtreDresde1841.webp',description:'Théâtre de Dresde en 1841'},
  {image5:'/Images/5LesThermesBadHomburg1845.webp',description:'Les thermes de Bad-Homburg 1845'},
  {image6:'/Images/5ChâteauLichstenstein1845.webp',description:'Château de Lichstenstein 1845'},
  {image7:'/Images/5pauqebotLoire.webp',description:'Paquebot de la Loire'},
  {image8:'/Images/5LaHaye1880.webp',description:'La Haye 1880'},
  {image9:'/Images/5Amsterdam1900.webp',description:'Amsterdam vers 1900'},
  

],
text:['A peine arrivé à Paris, Balzac, harassé de fatigue et perclus de douleurs, repart le 8 novembre 1843 au Havre récupérer ses malles qu’il avait fait expédier par mer, pour voyager plus léger au retour. Auparavant, il a pris la sage précaution de consulter son médecin et ami fidèle, le Docteur Nacquart. Celui-ci lui diagnostique bien une méningite due, selon lui, au surmenage ininterrompu de l’écrivain et lui prescrit pour une durée d’un mois « de fortes applications de sangsues et des remèdes adoucissants contre la névrose ». Comme à chaque retour de voyage, Balzac retrouve d’emblée son lot de difficultés parisiennes. Tout d’abord, sa pièce Pamela Giraud, présentée pendant son absence le 25 septembre au théâtre de la Gaîté, est loin de rencontrer le succès littéraire et donc financier escompté par l’auteur. D’autre part, Balzac apprend, sans doute en consultant le Journal des chemins de fer, hebdomadaire spécialisé créé en 1842, que la valeur des actions du Chemin de fer du Nord qu’il a achetées a baissé significativement durant son absence. Affaibli par la maladie, l’écrivain semble, cette fois-ci, las de cette routine immuablement composée de labeur continu, d’échecs successifs et d’attente interminable d’une union qui reste incertaine… il s’épanche auprès de Mme Hanska : « Mon Dieu ! Me retrouver ici, dans ce cabinet, après vous avoir vue, et pendant deux mois, m’y retrouver avec les mêmes idées qu’avant mon départ ! Avec le même désir, la même soif ! Dans une semaine, je ferai les mêmes courses, avec le même foyer au cœur, je voudrais diminuer le fardeau de ma dette, avec la même ardeur ! Et cependant, je vous ai vue ! »',

'La fin de l’année 1843 est consacrée aux soins et au repos. Malgré une santé encore vacillante dans les premiers mois de l’année suivante, Balzac poursuit en 1844 la rédaction de son œuvre magistrale La Comédie Humaine, en donnant  naissance, entre autres, au roman Modeste Mignon. Outre son activité littéraire, deux autres projets accaparent son énergie : résorber ses dettes de façon sérieuse, car il semble que Madame Hanska l’ait posé comme condition à leur mariage et faire l’acquisition d’une maison digne d’y loger sa princesse. De nombreuses publications et plusieurs avances de fonds assez importantes rendent possible la liquidation de ses dettes courantes. En enfant bien discipliné, calculs à la clé, il informe régulièrement Mme Hanska de l’amélioration de sa situation financière ; et c’est avec fierté et un optimiste débordant, que seul peut avoir un homme considérant ses dettes comme une partie intégrante de son univers, qu’il lui annonce en novembre : « […] Voilà mes dettes payées à 30 000 frs près. Donc, je puis mettre le prix des Jardies en terrain. Claret me donne 3 ans pour lui payer la maison en lui payant 5 % d’intérêts. […] Aussi n’ai-je aucune inquiétude sur l’avenir. » Ces « 30 000 francs près », soit environ 120 000 euros actuels, n’effraient nullement Balzac… Il n’a jamais été aussi près d’éponger toutes ses dettes et donc d’être « apte » au mariage avec Mme Hanska. Il reprend toute confiance en un avenir clément auprès de sa bien-aimée, d\'autant plus qu\'elle lui a annoncé les fiançailles de sa fille Anna. Un mois plus tard, il lui confie d\'une façon touchante : « Je m’occupe de notre bonheur. En 1846, nous aurons la plus délicieuse maison de Paris, je n’aurai plus un sou de dettes, et j’ai pour 500 000 frs de travail à peu près à faire dans La Comédie humaine sans compter l’exploitation de cette affaire qui représente au moins cela. Je suis donc, belle dame, un parti d’un million et plus, si je ne meurs pas ! Si je n’épouse pas, selon votre mot, une pauvresse, vous n’épousez pas non plus un pauvre. Nous serons deux charmants vieillards, unis par l’amour comme Sismondi et sa femme, malheur à qui restera le dernier, la vie lui sera bien amère. »',

'Après avoir réglé ses affaires de succession à Saint-Pétersbourg, Mme Hanska, de son côté, était retournée à Wierzchownia en mai 1844. En novembre, elle part s’installer à Dresde pour y passer l’hiver, accompagnée de sa fille et de son futur gendre, le comte Georges Mniszech. Aussitôt, Balzac lui propose de la rejoindre. Mais pour la deuxième fois, il doit essuyer son refus de le voir et attendre patiemment son bon vouloir...Ce n’est qu’à la mi-avril 1845 que Mme Hanska lui accorde l’autorisation de venir à Dresde. Balzac, pourtant encore affaibli par une série de maladies, décuple d’énergie pour préparer ce voyage qu’il espérait chaque jour, ainsi qu’il le clame à sa chère Eve : « J’ai passé ces 5 mois à me dire tous les soirs – Je pars demain. Je te verrai, ne fût-ce qu’un mois, ne fût-ce que dix minutes, mais je te verrai ! […] Je vais la revoir, une idée qui a souvent défrayé des voyages de 700 lieues ! J’ai tout envoyé promener, et La Comédie humaine et Les Paysans et La Presse et le public, et Chlendowski à qui je dois 10 feuilles de la Comédie humaine ! Enfin tout ! » Une semaine plus tard, le 25 avril, Balzac quitte Paris. Comme pour son retour de Saint-Pétersbourg, il emprunte sans doute alternativement malle-poste et chemin de fer, en passant par Francfort et Leipzig où il doit régler une affaire de réimpression de ses œuvres en allemand. Il arrive à Dresde le 1er mai et descend à l’hôtel Stadt Rom où il avait déjà séjourné lors de son retour de Saint-Pétersbourg en 1843. Il y occupe un appartement, réservé par Mme Hanska, au second étage, avec salon, chambre et bureau. Balzac n’a qu’à traverser la rue pour se rendre à l’hôtel de Saxe où réside sa bien-aimée… ',

'Il y fait la rencontre de Georges Mniszech, le fiancé d’Anna. Balzac se prend d’emblée de tendre amitié pour ce jeune comte polonais, collectionneur passionné de coléoptères au caractère doux et inoffensif. Les deux jeunes fiancés, plein d’insouciance que peuvent donner la jeunesse et la fortune, donnent le ton de ce séjour. Balzac, pour la première fois de sa vie, lâche prise et s’abandonne entièrement à cette vie légère : visites de la ville, sorties au théâtre, tout est divertissement où  le travail et les soucis d’argent n’ont plus leur place… Ainsi, sur l’initiative de Balzac, les quatre voyageurs se rebaptisent du nom de personnages du vaudeville Les saltimbanques, créé en 1838 au théâtre des Variétés et reprise en 1843 à Saint-Pétersbourg : l’écrivain se renomme Bilboquet, chef de la troupe des saltimbanques, Mme Hanska est Attala, la « femme sauvage », Anna devient Zéphirine, la « sauteuse » et Georges endosse le nom de Gringalet, le personnage « paillasse » de la troupe… Cependant, Dresde abrite une importante communauté d’émigrés polonais et le quatuor se voit vite exposé à leurs commérages acerbes. Balzac avait d’ailleurs prévenu Mme Hanska, dès son arrivée dans la ville, que « Dresde était une ville à cancans, [où] il était impossible d’y rester ».',

'En mai, ils partent donc s’installer à Bad-Homburg, station thermale au pied de la montagne du Taunus, à proximité de Francfort. Balzac et Mme Hanska y font la rencontre de Mme Sophie Kisséleff,  la belle sœur du chargé d’affaires de l’ambassade de Russie à Paris qui avait, en 1843, remis à l’écrivain son passeport. Joueuse passionnée, il est probable qu’elle ait entrainé le couple au Kursaal, le casino de la ville. Fin mai, la troupe s’achemine vers Cannstadt, ville d’eau dans la banlieue de Stuttgart où Mme Hanska suit une cure. Les journées continuent à être rythmées agréablement par des sorties, excursions, visites à des connaissances, telles que celle au comte Guillaume de Wurtemberg dans son château de Lichstenstein. C’est aussi durant ce séjour que prend forme le projet d’un voyage en France. Balzac se rend alors seul à Strasbourg au mois de juin afin de mettre au point, avec sa gouvernante Mme de Brugnol, toutes les modalités d’un séjour clandestin en France, le tsar interdisant à tous ses sujets d’y résider. Dès le mois de février, l’écrivain avait déjà pris la sage précaution de se faire établir un passeport où il faisait passer Mme Hanska pour sa sœur et Anna pour sa nièce…',

'A peine de retour à Cannstadt, Balzac part en compagnie de Mme Hanska et de sa fille à Karlsruhe, d’où ils rejoignent Strasbourg en remontant le Rhin. Ils quittent alors la ville le 7 juillet à bord de la malle-poste et arrivent à Paris deux jours plus tard. Balzac installe les deux femmes dans un petit appartement rue de La tour à Passy, près du sien situé rue Basse. Le séjour dans la capitale reste aussi secret que le voyage mais on peut imaginer l’entrain de Balzac à faire découvrir à sa belle polonaise son univers parisien tant aimé… En juillet, il les emmène visiter Fontainebleau et Rouen, puis c’est au tour de sa région natale, avec les villes d’Orléans, Blois et Tours qu’ils traversent peut-être à bord d’un bateau à vapeur de la compagnie générale des paquebots de la Loire. Si leur emploi du temps durant ce séjour reste discret, il semble cependant que les voyageurs se soient adonnés sans compter au plaisir d’achats d’antiquités et de brocantes. Tel le petit Poucet, Balzac jalonne avec ardeur leur trajet de factures d’antiquaires, d’autant plus facilement que Mme Hanska assure en grande partie leur financement et qu’elle semble partager ce goût avec l’écrivain. Il décrira cette passion pour la recherche et l’acquisition d’objets d’art à travers le personnage de Sylvain Pons, dans son roman Le Cousin Pons. Le bric-à-brac, tel qu’il le nomme, devient un univers à part entière qu’il décline sous toutes les formes : ainsi Balzac parle de bricabracomanie, de bricabracologie, de l’action de bricabraquer et même du royaume de la Bricabraquie !… De retour à Paris au mois d’août, ils repartent aussitôt à Strasbourg par la malle-poste. De là, à bord du bateau à vapeur L’Elberfeld, ils descendent le Rhin en direction de la Hollande : ce sont des escales à La Haye, Amsterdam, Rotterdam. Ils continuent vers la Belgique, avec visite d’Anvers et Bruxelles. Les achats d’antiquités, en particulier chez l’antiquaire Schwaab, s’accumulent au fur et à mesure… ',

'Le 27 août, tandis que Mme Hanska et Anna rejoignent Cologne et Karlsruhe, Balzac prend le chemin du retour pour Paris. Il atteint Gand en diligence, de là prend le train pour Lille puis la malle-poste pour rejoindre Paris où il arrive le 30 août. Plus de quatre mois passés auprès de son amour, dans une ambiance de détente absolue, lui rendent le retour à Paris déprimant : « Tout m’est indifférent ici de ce qui ne vous concerne pas, pour ne pas dire odieux, et c’est à tel point qu’hier, accablé de fatigue, barbe de 8 jours, poussière de 22 heures de route, linge sale, costume de voyage, je suis allé chez Froment-Meurice avant de venir ici ». (Mr Froment-Meurice est un célèbre orfèvre chez qui Mme Hanska et Anna avaient pris l’habitude de passer commande…)',

'En effet, Balzac, à présent âgé de 46 ans, semble ne plus avoir l’énergie ni le goût de continuer cette vie de labeur qui l’a littéralement usé…Seule l’idée de rejoindre Mme Hanska n’importe où dans le monde et celle de leur préparer un nid douillet à Paris réussissent à actionner le peu de ressort qui lui reste. Il reprend donc ses prospections immobilières, avec l’assentiment de Mme Hanska qui lui fait parvenir, en octobre, une somme d’environ 130 000 francs - baptisé par Balzac « trésor louloup » -  pour financer l’achat et l’aménagement d’une maison. Obéissant à sa manie pas toujours très heureuse de spéculer, il s’empresse d’investir une grande partie de la somme dans des actions des chemins de fer du Nord…  Le 24 septembre, il rejoint Mme Hanska pour un séjour éclair de 6 jours à Baden. Il est de retour à Paris le 4 octobre. Le 22 du même mois, il repart par malle-poste à Chalons sur Saône où il retrouve Eve, Anna et Georges. Ensemble, ils descendent la Saône à bord d’un bateau à vapeur jusqu’à Lyon, puis continuent sur le Rhône jusqu’à Arles, en passant par Valence. En avance sur le domaine maritime, les compagnies de transport fluvial de passagers se multiplient dès 1820 dans une concurrence forcenée. La ligne régulière entre Lyon et Arles, empruntée par nos quatre compagnons, est assuré par la Compagnie générale des bateaux à vapeur, créé en 1830 par Church. C’est à bord d’un bateau aux dimensions modestes mais rivalisant de luxe dans son aménagement que la troupe des saltimbanques savourent tranquillement cette descente du fleuve, profitant du confort d’un grand et petit salon, d’une spacieuse salle à manger, d’un restaurant, d’un compartiment réservé aux fumeurs et d’un autre aux dames ; le tout orné précieusement avec bois, glaces et dorures. Près d’un million de voyageurs empruntent annuellement le Rhône dans les années 1840, dont les trois quart en descente. Cependant, l’expansion du chemin de fer va rapidement porter un coup fatal au transport fluvial des voyageurs : alors qu’au milieu du 19ème siècle, les bateaux assurent environ 40% du trafic national, leur contribution n’est plus que de 15% en 1876.',

'Même si la navigation semble moins risquée sur un fleuve qu’en pleine mer, elle n’est cependant pas exempte de tout danger. En effet, le gel, le brouillard, les sécheresses comme les crues peuvent considérablement altérer la navigation, voire l’interrompre plusieurs mois chaque année. A cette époque, il n’est pas rare que des bateaux viennent heurter les piliers des ponts ou endommagent leur cheminée pas suffisamment inclinée pour passer sous les arcades, par manque de visibilité. Les voyageurs atteignent Marseille au bout de quelques jours et s’installent dans un appartement à l’hôtel d’Orient, réservé par le poète Joseph Méry, grand ami de Balzac. Après une visite de Toulon, ils embarquent à Marseille à bord du bateau à vapeur Léonidas pour rejoindre Naples, avec escale à Civitavecchia. Le sol italien n’était pas totalement inconnu à Balzac. Il avait en effet eu l’occasion de se rendre à Turin en 1836, accompagné secrètement de son amante Caroline Marbouty… A peine arrivés à Naples le 5 novembre, Balzac réembarque seul, 3 jours plus tard, à bord du Tancrède pour retourner à Marseille. Lors de l’escale à Livourne, il en profite pour visiter Pise, malgré une pluie battante. Il retrouve à Marseille son ami Joseph Méry qui le guide à travers la ville et le mène dans des boutiques d’antiquité. Balzac fait de nombreuses acquisitions auprès de l’antiquaire Lazard, avant de reprendre, le 14 novembre, la route de Paris par malle-poste. Le voyage dure trois jours.',

'Alors que Balzac reprend très tranquillement son travail littéraire et plus assidûment ses recherches immobilières et d’antiquités, Mme Hanska et les deux fiancés passent la fin de l’automne, l’hiver et le printemps 1846 en Italie. Le 16 mars 1846, sur la demande de Mme Hanska, Balzac part la rejoindre à Rome, abandonnant sur le champ ses affaires et ses travaux en cours. Au préalable, il s’est procuré un laissez-passer pour la douane des Etats pontificaux par l’intermédiaire du directeur de la Villa Médicis, le peintre Schnetz. Il prend la malle-poste pour Lyon puis pour Marseille et embarque le 21 mars à bord du Mentor pour Rome, avec escale à Civitavecchia. Il arrive à destination le 25 mars.Balzac, grand amateur d’art, est ébloui par cette ville qu’il s’était toujours promis de visiter. Les journées se passent à admirer les nombreux monuments et musées de la capitale : la galerie Borghèse, la Villa Doria-Pamphili, les musées du Vatican, le Palais Sciarra… Mme Hanska fait rencontrer à Balzac l’un de ses parents, Michelangelo Caetani, prince de Taneo. Ce grand érudit va accompagner les quatre touristes tout au long du séjour : il les introduit dans des collections privées, les guide lors d’excursions archéologiques, comme celle des Thermes de Caracalla et aide Balzac dans ses négociations avec les marchands d’antiquités. Ainsi, l’écrivain fait l’acquisition « d’un Sébastien del Piombo, un Bronzino, et un Mirevelt de la dernière beauté ». Mais surtout, il fait partager à Balzac ses immenses connaissances sur Dante. Il l’invite d’ailleurs à assister aux conférences organisées sur l’illustre auteur au Palais Farnèse de Rome. Une sincère amitié se lie entre les deux hommes… Pour clore le tout, Balzac a la chance d’assister, durant la semaine sainte, à une audience publique auprès du Pape Grégoire XVI qui lui béni un chapelet et un scapulaire destinés à sa mère.',

'Le séjour à Rome dure presqu’un mois, à l’issue duquel Balzac ne tarit pas d’éloges sur la ville éternelle. Ainsi écrit-il à sa sœur Laure : « J’ai vu tout Rome, depuis A jusqu’à Z. L’illumination du dôme de Saint-Pierre le jour de Pâques, vaut à elle seule le voyage. Mais comme on peut en dire autant de la bénédiction « Urbi et Orbi », de Saint-Pierre, du Vatican, des ruines, il se trouve que mon voyage peut compter pour dix. […] Je suis si content de Rome que j’ai l’intention d’y passer l’hiver prochain tout entier, car je veux tout en savoir.[…] Rome, dans le peu de temps que j’y suis resté, sera l’un des plus grands et des plus beaux souvenirs de ma vie […] » En ajoutant toutefois une critique : « Malheureusement Rome est chère, elle a autant de mendiants que d’habitants, ce qui rend les visites aux palais et aux galeries d’une impossibilité majuscule. » Le 22 avril 1846, la troupe quitte Rome. Ils embarquent à Civitavecchia pour se rendre à Gênes. Après un séjour au lac d’Orta puis au lac Majeur, ils entrent en Suisse par le Simplon, font une halte à Genève puis Berne et atteignent enfin Bâle le 16 mai. Si les paysages changent, la frénésie d’achats de Balzac reste la même : « Je cherche des tableaux bon marché sur ma route et je voudrais trouver des Hobbema et des Holbein pour quelques écus, car je poursuis avec acharnement l’œuvre de mon mobilier. »',

'Avant que Balzac ne reprenne la route pour Paris, Mme Hanska lui annonce une nouvelle pour le moins inattendue : elle est enceinte, à l’âge de 42 ans… C’est sans doute bouleversé par cet évènement inespéré que Balzac rejoint Paris en malle-poste, en passant par Heidelberg et Strasbourg. Il y arrive le 28 mai. Le 30 août, notre voyageur infatigable reprend la route de l’Allemagne pour rejoindre sa nouvelle famille à Creuznach, d’où ils partent ensemble pour Mayence. Balzac se rend seul à Metz pour essayer d’organiser, avec son ancien ami Le Préfet de la Moselle, un mariage secret avec Mme Hanska. Elle ne peut en effet se marier avec un étranger sans l’autorisation du tsar russe. Il est de retour à Paris le 15 septembre. Balzac se remet de plus belle à la recherche d’une demeure digne d’accueillir son Eve chérie et cet enfant à venir qu’il s’imagine déjà être un garçon qu’il baptisera Victor-Honoré. Ses prospections aboutissent finalement à l’achat, le 28 septembre, d’une maison située Rue Fortunée à Paris et qui s’avère nécessiter de nombreux travaux... Le 11 octobre 1846, la dernière condition posée par Mme Hanska à son mariage avec Balzac est enfin satisfaite : Anna épouse Georges Mniszech à Wiesbaden. L’écrivain y assiste en tant que témoin de mariage et retourne dans la capitale le 17 octobre. L’état euphorique de Balzac ne dure malheureusement pas longtemps. Le 1er décembre, alors qu’il s’apprête à aller chercher Eve à Dresde pour la ramener dans leur demeure aménagée avec amour, il reçoit une lettre dans laquelle elle lui annonce une terrible nouvelle : elle a fait une fausse couche… Balzac est atterré et vidé de toute énergie vitale. Il exprime sa douleur  à  Mme Hanska : « Je viens de pleurer trois heures, comme un enfant. […] D’aujourd’hui, jour bien cruel pour moi, car c’est la mort de bien des espérances, je me replonge dans la fournaise ardente d’où je sortais pour te ramener ici. Tout m’est odieux. Tous mes efforts pour te faire un palais inconnu, tous mes succès, tout devient des épées dirigées sur moi »… Cette douleur est d’autant plus difficile à supporter qu’Eve lui interdit de la rejoindre à Dresde… Mais quand donc pourra-t-il être enfin apaisé… ?',]

 },
 {id:6,
  mainImage:'/Images/6mainImage.webp',
  title:'Wierzchownia enfin !...',
  image: [
    {image1:'/Images/6ChâteauWisniowiec 1850.webp', description:"Château de Wisniowiec 1850"},
  {image2:'/Images/6JournalDébatsDimanche15août1847.webp',description:'Journal des Débats du dimanche 15 août 1847'},
  {image3:'/Images/6GareNord1846.webp',description:'Gare du Nord 1846'},
  {image4:'/Images/6LaGrandeSynagogueBrody1900.webp',description:'La grande synagogue de Brody vers 1900'},
  {image5:'/Images/6Kibitka19èmeSiècle.webp',description:'Kibitka 19ème siècle'},
  {image6:'/Images/6BerditchevFin19èmeSiècle.webp',description:'Berdytchiv à la fin du 19ème siècle'},
  {image7:'/Images/6LeChâteauWierschownia.webp',description:'Le château de Verkhivnia'},
  {image8:'/Images/6Kiev1890.webp',description:'Kiev 1890 : entrée du monastère Laure des Grottes'},
  {image9:'/Images/6KyivFin19èmeSiècleArtèrePrincipale.webp',description:'Kiev fin du 19ème siècle : artère principale'},
],
text:['Submergé par la tristesse, Balzac a bien du mal à se remettre à son activité littéraire, prostré dans une léthargie qui l’empêche de produire une seul phrase : « Hier, j’ai eu la constance de rester assis à ma table, comme un écolier au piquet, pendant toute la journée, depuis mon réveil jusqu’à mon coucher, sans pouvoir extraire de mon cerveau deux lignes, ni quoi que ce soit qui ressemble à une pensée. » ',

'Petit à petit, l’énergie créatrice reprend malgré tout le dessus et Balzac se relance dans la rédaction de ses deux derniers chefs d’œuvre, La cousine Bette et Le cousin Pons, deux romans d’une noirceur qui semble bien refléter son état d’esprit. Après leur mariage, Anna et Georges sont partis visiter Berlin et Breslau, laissant seule Mme Hanska à Dresde. Fin janvier 1847, enfin décidée à revoir Balzac, elle lui demande de venir la chercher à Francfort, à l’hôtel Weidenbusch, pour séjourner incognito à Paris. Balzac, en bon moujik transi d’amour, quitte aussitôt Paris le 4 février pour ramener sa dulcinée le 11 février à Paris. Pour la première fois depuis le début de leur relation, ils expérimentent durant plus de deux mois une vraie vie commune de couple dans l’appartement loué par Balzac rue Neuve-de-Berry. Les journées s’écoulent tendrement, ponctuées de promenades dans les quartiers de Paris et de sorties à l’Opéra… Début mai, Balzac raccompagne Mme Hanska à Francfort, en passant par Forbach. Il est de retour à Paris le 13 mai, fourbu de fatigue. Mme Hanska, quant à elle, rejoint ses terres ukrainiennes en faisant une halte tout d’abord au château de Bakonczyce appartenant à la mère de Georges, puis au château de Wisniowiec, près de Radziwilloff, domaine du frère de Georges, André Mniszech. De nouveau en compagnie de sa fille et de son gendre, elle retrouve enfin, fin juin 1847, sa résidence de Wierzchownia, après une absence de plus de deux ans et demi… En attendant que sa bien-aimée lui donne l’autorisation de venir en Ukraine, Balzac use l’énergie qui lui reste à superviser les travaux de la maison Rue Fortunée, qui s’avèrent être assez conséquents et à acquérir toutes sortes d’objets de décoration. Il rend compte d’ailleurs consciencieusement à Mme Hanska des dépenses faites sur le « trésor louloup », en la convaincant immanquablement de son flair de bricabracomane éclairé…',

'Le train passe par Valenciennes et fait une halte à Bruxelles. Si Balzac s’inquiétait de ne connaître aucun mot d’allemand à part « Milk » (lait), il a la chance de faire des rencontres très utiles tout au long du voyage : à la gare de Bruxelles, il tombe par hasard sur Mme Kisséleff, dont il a fait la connaissance lors du séjour à Bad-Homburg avec Mme Hanska et qui s’apprête à rejoindre sa résidence en Allemagne. Au grand soulagement de Balzac, ils font donc ensemble le trajet en train jusqu’à Cologne, en passant par Liège et Aix-la-Chapelle. Balzac passe la nuit du 6 décembre dans la ville avant de reprendre le train le lendemain pour Hamm, en passant par Düsseldorf. Au moment de récupérer ses bagages à Hamm pour poursuivre son périple en Schnell-post, Balzac, sans doute seul voyageur français, semble paniqué par cette foule étrangère qui s’agite autour de lui et contre laquelle il peste : « On parle de la furie française, on parle de chasse-neige, rien n’est comparable aux tempêtes de l’égoïsme que développent les voyageurs »',

'Heureusement, il est encore une fois pris sous l’aile d’un voyageur bienveillant de langue allemande, rencontré par hasard. C’est ainsi qu’il fait le trajet en Schnell-post puis Extra-post jusqu’à Hanovre, où il doit reprendre le train, avec un certain Docteur Roth, médecin de l’Ambassade d’Autriche. Sa compagnie est d’autant plus agréable à Balzac qu’il parle très bien français, ayant vécu quelques années en France, et surtout qu’il se révèle être un collectionneur fort instruit sur les porcelaines et céramiques… ',

'Quant aux services de transports allemands, Balzac n’adoucit pas le jugement qu’il en portait déjà en 1843, à son retour de Saint-Pétersbourg. Il considère que « l’Allemagne… c’est le pays le plus tire-laine qu’[il] sache » et que les allemands « semblent avoir plusieurs jours à eux dans la journée, ils ont l’air de pouvoir faire des emprunts sur l’éternité. » !... Le 8 septembre à Hanovre, il monte à nouveau dans le train, en compagnie du Dr Roth. Ils traversent les villes de Magdebourg, Berlin puis Breslau. Le cher docteur, devant continuer son chemin vers Vienne, confie alors Balzac aux bons soins d’un autre voyageur rencontré par hasard, et qui s’avère être le frère du consul russe à Cracovie. C’est en sa nouvelle compagnie que Balzac atteint en train Gleiwitz, alors ville de Silésie puis, à bord de la diligence, Cracovie le 9 septembre après-midi. Balzac y admire la cathédrale et les nombreuses églises qui, selon lui, égalent en beauté les églises baroques romaines. Il est nettement moins élogieux sur la ville même qu’il qualifie de « cadavre d’une capitale »… ',

'Le lendemain, Balzac traverse la Galicie à bord de la malle-poste en direction de Brody. Il est frappé par la misère qu’il rencontre le long des chemins : « Sur tous les chemins, des spectres affamés, et qu’on chassait à coup de fouet, venaient assaillir les voitures, d’où tombaient, disons-le, d’abondantes aumônes ». Il s’arrête au château de Przeworsk, invité à dîner par le prince Henri Lubomirski, un parent de Mme Hanska. Puis il poursuit son chemin pour arriver à Brody le 11 septembre au petit matin. Cela fait sept jours qu’il est parti de Paris. Il descend à l’hôtel de Russie, qui lui apparaît peu engageant : « Nos prisons sont d’un aspect plus réjouissant que celui des chambres de l’auberge intitulé l’hôtel de Russie, le premier hôtel de Brody ».',

'L’arrivée de Balzac coïncide avec le Nouvel An Juif et le voyageur ne trouve que portes closes. Pris en charge jusqu’à maintenant, l’écrivain sent que les difficultés du voyage vont réellement commencer : « Pour moi, mon voyage ne commençait qu’à Brody, car les cent lieues qui séparent Berditcheff de Brody me paraissaient plus difficiles à franchir que les sept cents lieues de Paris à Brody » Encore une fois, un heureux hasard veut que le consul de Russie à Brody loge dans le même hôtel que Balzac. Il accepte de rédiger une lettre à l’attention du directeur des douanes russes, le Général Hackel, pour lui demander si notre voyageur est en règle pour passer la frontière. Dès le retour positif de sa requête, l’aubergiste prête voiture et chevaux à Balzac pour rejoindre Radziviloff dans la journée. Balzac décrit la ville frontalière comme un « amas de cabanes en bois qui se tiennent debout par une faveur spéciale de la Providence envers la Russie. Pas un mètre de pavé, toutes les voies sont de terre battue. ». Il passe néanmoins une soirée réconfortante dans la demeure du Général.',

'Le lendemain soir, accompagné par un soldat mis à disposition, il s’embarque pour Berditchev, à bord d’une kibitka, « voiture de bois et d’osier, traînée avec une vélocité de locomotive,[qui] vous traduit dans tous les os les moindres aspérités du chemin avec une fidélité cruelle ». Ils traversent les villes de Dubno, Jitomir et arrivent à Berditchev le 13 septembre à midi. Là encore, le verdict de Balzac est tranchant : « Je vis avec étonnement les maisons dansant la polka, c’est-à-dire inclinées toutes, les unes sur la hanche droite, les autres sur la gauche, quelques-unes donnant du nez, la plupart disloquées, beaucoup d’entre elles plus petites que nos baraques de foire, et propres comme des toits à porcs. C’est un spectacle tellement inattendu pour l’Européen, pour un Parisien, qu’il faut le voir répété par plusieurs villes avant de s’y habituer.» Ne trouvant aucun autre moyen de transport, Balzac termine bien piteusement les 60 kms restants le séparant de Wierzchownia à bord d’un bouda, «panier oblong posé sur une perche accompagné de quatre roues ». Il découvre alors un paysage « de vraies steppes, car l’Ukraine commence à Berditchev. C’est le désert, le royaume du blé, c’est la prairie de Cooper et son silence ».',

'Trois heures et demie plus tard, Balzac aperçoit enfin le château de Mme Hanska, « espèce de Louvre, de temple grec, doré par le soleil couchant, dominant une vallée », au milieu d’un immense parc de plus de 21 000 hectares, le tout posé au milieu de nulle part. Si l’extérieur a des allures princières, Balzac découvre un intérieur beaucoup plus austère : beaucoup de pièces du château sont meublées au minimum, aucune tenture ne vient décorer les murs, le chauffage est assuré par de la paille brûlé dans des poêles. On peut imaginer ce que doit y être la vie en plein hiver… Les services variés de plus de 1 000 serfs et de 300 domestiques assurent une complète autarcie aux habitants du domaine. Balzac, exténué, s’installe dans l’appartement que lui destine Mme Hanska, « un délicieux petit appartement composé d’un salon, un cabinet et une chambre à coucher ; le cabinet est en stuc rose, avec une cheminée, des tapis superbes et des meubles commodes, les croisés sont toutes en glace sans tain, en sorte qu’[il] voi[t] le paysage de tous les côtés. »',

'Après quelques jours de récupération, Balzac se rend à Kiev, à 150 kms de là, pour régulariser son permis de séjour auprès du Général Bibikoff, gouverneur général de Kiev. Il semble que l’écrivain n’ait pas été ébloui outre mesure par la ville ukrainienne, qu’il nomme pourtant curieusement « la Rome du Nord ». Son seul commentaire se résume à : « C’est beau à voir une fois »… Il paraît bien plutôt avoir été séduit, dans sa vanité, par un riche paysan qui lui confie avoir lu tous ses ouvrages et brûler un cierge pour l’écrivain toutes les semaines !',

'Balzac savoure ce séjour à Wierzchownia, l’univers de sa tendre aimée. Il passe les journées en toute tranquillité, profitant du moment présent, bien loin des affaires compliquées et des créanciers parisiens. S’il consacre peu de temps au travail littéraire, sa manie incurable de la spéculation ne le laisse pas en paix : l’observation des forêts entourant le château fait germer l’idée d’exploiter les chênes pour approvisionner en traverses tous les chemins de fer européens en construction… Projet aussi vite abandonné, face au manque de transports de la marchandise. Balzac décide cependant de rentrer à Paris plus tôt que prévu, sans doute préoccupé par les affaires qu’il y a laissées en cours, mais aussi peut-être parce que Mme Hanska ne semble absolument pas décidée à l’épouser.',

'C’est donc en plein hiver russe, par des températures avoisinant les moins 25 °, que Balzac se met courageusement en route pour le retour, fin janvier 1848 : « Je vais faire ce voyage par un tel froid qu’il faut prendre toutes sortes de dispositions […], je viens d’essayer un manteau à mettre par-dessus la pelisse, qui est comme une muraille. Il y a quelques jours, en me promenant en traineau, je me suis aperçu que la pelisse de renard de Sibérie était comme une feuille de papier brouillard devant ce froid terrible » Comme à l’aller, il parcourt la distance jusqu’à Berditchev en bouda, puis continue sans doute en diligence jusqu’à Lviv (anciennement nommée Leopol). De là, il gagne Cracovie où il monte à bord du train le menant à Breslau le 6 février. Ne résistant pas au plaisir des antiquités, il fait un crochet par Dresde où il « rend visite » à Louis Wolf, antiquaire du roi de Saxe. Le 11 février, il est à Francfort, puis effectue un nouveau détour pour rencontrer l’antiquaire Schwaab à Mayence. Le 15 février, il prend le train à Francfort pour rejoindre Paris et sa nouvelle demeure Rue fortunée. Une semaine plus tard, la Révolution de Février 1848 éclate…'
]
 },
 {id:7,
  mainImage:'/Images/7mainImage.webp',
  title:'Le mariage au bout du voyage...',
  image: [
    {image1:'/Images/7EgliseSainte-BarbeBerditchev.webp', description:"Eglise de Sainte-Barbe à Berditchev"},
  {image2:'/Images/7PlaqueCommémorativeMariage.webp',description:'Plaque commémorative du mariage d\'Honoré de Balzac et d\'Evelyne Hanska'},
  {image3:'/Images/7MaisonMrMmeBalzac,.webp',description:'Maison de Mr et Mme de Balzac, rue Fortunéeà Paris'},
  {image4:'/Images/4IlePlaceCronstadt1843.webp',description:'Ile et place de Cronstadt 1843'},
  {image5:'/Images/4QuaiAnglais1850.webp',description:'Quai des Anglais vers 1850'},
  {image6:'/Images/4QuaiNévaBalzac.webp',description:'Quai de la Néva, où débarque Balzac.Photo datant des années 1900'},
  {image7:'/Images/4MadameHanskaSalonBleu.webp',description:'Madame Hanska dans son salon bleu.Aquarelle peinte par Karl Ivanovitch Kollman en 1843, et que Mme Hanska offrira à Balzac en juin 1844.'},
  {image8:'/Images/4Riga1840.webp',description:'Riga vers 1840'},
  {image9:'/Images/5Marseille1880.webp',description:'Marseille vers 1880'},
],
text:['Balzac peste contre cette révolution qui amplifie ses difficultés financières. Cette période de chaos met à mal non seulement la presse, l’écrivain se plaint de ce qu’il n’y a « plus de journaux constitués comme ils l’étaient, partant plus de feuilleton, plus de recettes littéraires », mais de plus, elle entraine une chute de la valeur des fameuses actions des chemins de fer du Nord. Et la maison de la Rue Fortunée continue à engloutir des sommes d’argent non négligeables…      ',

'Soucieux de pouvoir retourner en Ukraine, il se tourne alors vers la solution de repli qu’est le théâtre, en proposant des adaptations à la scène de certains de ses romans, comme Le père Goriot. Enfin, ce que Balzac considère sans doute comme le plus grave, la Révolution complexifie grandement toute entrée d’un Français en Russie… Afin d’obtenir un passeport et l’autorisation d’entrer en Russie,  il entreprend d’écrire deux lettres qu’il remet au chargé d’Affaires Nicolas Kisséleff, l’une étant destinée au comte Ouvaroff, ministre russe de l’Instruction Publique et l’autre au ministre russe de la Police, le comte Orloff.',

' Celui-ci se charge alors d’envoyer au tsar un rapport récapitulatif qui témoigne en faveur d’une autorisation d’entrée pour l’écrivain : «  Considérant la conduite irréprochable de Balzac lors de son dernier séjour en Russie, et la requête du comte Ouvaroff à son sujet, de mon côté, je croirais possible de satisfaire à la demande de Balzac de lui permettre de venir en Russie […] Me soumettant entièrement à ce sujet à la Haute décision de Votre Majesté Impériale, je suis heureux de présenter avec cela les lettres originales de Balzac, adressées au comte Ouvaroff et à moi-même, ainsi que les recommandations de ce dernier concernant cet étranger. »',

'La réponse du tsar est courte mais sans ambigüité : « Oui, mais avec une stricte surveillance. » Balzac obtient son passeport à la Préfecture de Police le 22 août et les visas à la légation russe une semaine plus tard. Il écrit, dans la foulée, une lettre au directeur des douanes russes, le Général Hackel, pour l’avertir de son arrivée prochaine et de son intention, voyageant seul et ne parlant pas l’allemand, de faire douaner ses bagages à Paris et de les faire expédier à la douane de Radziwilloff.',
'Il ne manque pas d’ajouter avec humour : « La Russie est maintenant ma maîtresse et la France ma femme légitime ; et, comme beaucoup de maris, je serai plus souvent chez ma maîtresse que chez ma femme »… Le 19 septembre 1848, Balzac se rend à la Gare du Nord pour prendre le train du soir en direction de Cologne. Les tronçons de chemin de fer manquants qui l’avaient obligé à voyager en Schnell-post l’année dernière, sont à présent mis en service. Le trajet Paris – Cracovie ne dure plus que 60 heures, contre 90 heures en 1847.',

'Balzac semble avoir fait quelques haltes sur le chemin car il n’arrive à Brody que le 26 septembre et passe la frontière à Radziwilloff le lendemain. Il fait une dernière escale de quelques jours au château de Wisniowiec chez André Mniszech, qui l’accompagne ensuite à Wierzchownia le 2 octobre 1848. Quant aux bagages, expédiés à part à la douane de Radziwilloff, ils n’arriveront à destination que le 6 décembre… L’écrivain s’installe à nouveau dans cette vie coupée de tout, tellement coupée de tout qu’il semble n’en plus éprouver le même enthousiasme… Sa santé est fragile, il est devenu un vieil homme avant l’âge, littéralement usé. Peut-être aussi que l’attitude de Mme Hanska le déçoit par rapport à tout ce qu’il avait pu rêver de leur réunion. Ainsi se confie-t-il à sa mère dans une lettre : « Les personnes avec lesquelles je vis sont excellentes pour moi, mais je ne suis encore qu’un hôte très choyé et un ami dans la véritable acceptation du terme. On connaît ici toutes les personnes de ma famille, et mes chagrins sont très vivement partagés ; mais que faire contre des impossibilités ? »',

'De plus, il semble que quelques frictions apparaissent entre les deux amants à propos des dépenses que Balzac a faites pour l’aménagement de la Rue Fortunée : il a dépensé en proportion égale de son amour pour la belle Eve, c’est-à-dire énormément. C’est découragé qu’il avoue à sa sœur, en décembre de la même année : « A 50 ans avoir encore 100 000 francs de dettes, et ne pas être fixé sur une question qui est toute ma vie et mon bonheur, voilà la thèse de l’année 1849. » Balzac n’entreprend pratiquement rien durant ce second séjour, sa santé se dégradant de plus en plus : il souffre à présent d’hypertrophie du cœur qui le laisse essoufflé au moindre effort. Il est obligé de renoncer au projet d’excursion à Odessa, ou plus près, à Kiev, mais aussi, plus tard, à un retour à Paris qu’il avait prévu en hiver 1849 pour s’occuper de ses affaires.',

'C’est en proie à la dépression qu’il se livre à son amie de toujours, Mme Zulma Carraud : « Comme la vie est autre vue du haut de cinquante ans ! et que souvent nous sommes loin de nos espérances ! […] Quelle rapidité pour l’éclosion du mal et quels obstacles pour les choses du bonheur ! Non ! c’est à donner le dégoût de la vie. Il y a 3 ans que j’arrange un nid et qui a coûté ici une fortune (hélas !) et il y manque les oiseaux. Quand viendront-ils ? Les années courent, nous vieillissons et tout se flétrira, même les étoffes et les meubles du nid. Vous voyez, chère, que tout n’est pas rose, pas même pour celles qui, en apparence, ont la fortune. »',

'Mme Hanska, à qui le tsar avait refusé de conserver ses terres en cas de mariage avec un étranger, franchit finalement ce pas tant espéré par Balzac depuis des années : en février 1850, elle prend la décision de donner ses terres et son domaine à sa fille, afin de pouvoir l’épouser et l’accompagner en France. L’état de santé de Balzac n’est sans doute pas étranger à son changement d’attitude… ',

'Après des démarches effectuées par Anna et Georges auprès de l’évêque de Jitomir, le mariage est enfin célébré le 2 mars 1850, à l’église Sainte-Barbe de Berditchev par l’abbé Victor Ozarowski, en toute intimité Balzac annonce l’heureuse nouvelle à sa fidèle amie Mme Carraud, d’une façon émouvante : « Donc, il y a 3 jours, j’ai épousé…Cette union est, je crois, la récompense que Dieu me tenait en réserve pour tant d’adversité, d’années de travail, de difficultés subies et surmontées. Je n’ai eu ni jeunesse heureuse ni printemps fleuri ; j’aurai le plus brillant été le plus doux de tous les automnes […]. »',

'Le 24 avril, à bord d’une berline achetée à Berlin, le couple quitte Wierzchownia en direction de Paris. Ce qui aurait été un voyage de noces heureux s’il avait été entrepris quelques années auparavant, s’avère être un parcours de souffrance pour Balzac et d’inquiétude pour Eve. Leur chemin de retour passe par les villes de Brody, Cracovie, Dresde où le couple ne résiste pas à l’achat de bijoux et antiquités et où Balzac demande par lettre à sa mère de tenir prête la demeure de la Rue fortunée pour leur arrivée le 20 ou 21 mai.',

'Après avoir dépassé les villes de Francfort et de Strasbourg, le couple arrive enfin à Paris dans la soirée. Balzac qui avait sans doute rêvé des millions de fois l’arrivée de sa femme chérie dans leur demeure conjugale, est encore une fois confronté à une réalité amère : le domestique devant les accueillir n’est pas là ; il faudra appeler un serrurier en pleine nuit et forcer la porte… L’écrivain n’aura que peu de temps pour savourer son rêve qui l’habite depuis 17 ans. Après d’atroces souffrances, il s’éteint dans la nuit du 17 au 18 août 1850.  ']
 },
 {id:8,
  mainImage:'/Images/8mainImage.webp',
  title:'BIBLIOGRAPHIE',
  image: [
    {image1:'/Images/4PortDunkerque1850.webp',description:'Port de Dunkerque vers 1850'},
  
 {image2:'/Images/4PlaqueCommémorativepassageBalzacTauragé10octobre184310octobre2013.webp',description:'Plaque commémorative du passage de Balzac à Tauragé le 10 octobre 1843, inaugurée le 10 octobre 2013'},
 {image3:'/Images/1mainImage.webp',description:''},
  {image4:'/Images/2mainImage.webp',description:''},
  {image5:'/Images/3mainImage.webp',description:''},
  {image6:'/Images/4mainImage.webp',description:''},
  {image7:'/Images/5mainImage.webp',description:''},
  {image8:'/Images/6mainImage.webp',description:''},
  {image9:'/Images/7mainImage.webp',description:''},
  
 
],
text:['',
'<h2>OUVRAGES DE REFERENCE</h2><p>Roger PIERROT, Honoré de Balzac, Fayard, 1994</p><p>Honoré DE BALZAC, Lettres à Madame Hanska, Robert Laffont, 1990</p>',
'<h2>OUVRAGES COMPLEMENTAIRES</h2><p>Stefan ZWEIG, Balzac. Le roman de sa vie, Albin Michel, 1950</p>',
'<h2>Voyage à Neuchâtel et Genève</h2><p>Gérard JOLY, La poste aux chevaux en 1833</p><p>Le Magasin pittoresque, 1833</p><p>Patrick MARCHAND, Le maître de poste et le messager, les transports publics en France au temps des chevaux, Paris, Belin, 2006</p>',
'<h2>Voyage à Vienne</h2><p>Martine GÄRTNER, Balzac et l’Allemagne, L’Harmattan, 2000</p><p>Adolphe VON SCHADEN, Nouveau Guide des étrangers dans Munich et ses environs,  Munich,     Librairie Joseph Lindauer, 1835</p>',
'',

'<h2>Voyage à Saint-Pétersbourg</h2><p>Sophie de KORWIN-PIOTROWSKA, Balzac et le monde slave, Slatkine, 1976</p><p>Natalia SMIRNOVA,  Saint-Pétersbourg, ou l’enlèvement d’Europe, Olizane, 1999</p><p>M. CADOT, « Les débuts de la navigation à vapeur et l’émigration française en Russie »: Cahiers du monde russe et soviétique, vol. 4, n°4, octobre-décembre 1963</p><p>Rick ARCHBOLD et Robert BALLARD, Les Grands Paquebots disparus, Glénat, 1997</p><p>Catalogue exposition Balzac dans l’Empire russe. De la Russie à l’Ukraine, Paris-Musées – Editions des Cendres, 1993</p>',
'',
'<h2>Voyage à travers l’Europe</h2><p>Bernard LE SUEUR, L’évolution de la navigation intérieure et de ses métiers, XIXe – XXe siècle. [Ouvrage collectif], Balzac et l’Italie. Lectures croisées, Paris-Musées – Editions des Cendres, 2003</p><p>Raffaele de CESARE, Balzac a Roma, dans : Balzac e Manzoni e altri studi su Balzac e l’Italia, Vita e Pensiero, 1963</p>',
'<h2>Voyage à Verkhivnia :</h2><p>Honoré de Balzac, Russie-express (Lettre sur Kiew), Edition NC, 2010</p>',
]
 },
]