export const projects=[
{id:1,
title: "CHAUDIERE Ust-Chorna",
image:"/Images/gravureLacLeman.webp",
date:"novembre 2022",
shortText:"Il s’agit de mettre en place une nouvelle chaudière avant les mois d’hiver afin de permettre à tous les déplacés (actuels et futurs) d’être accueillis dans ces locaux et d’avoir accès à un chauffage et eau chaude.Le chauffage bois permettra à la communauté de réaliser des économies, le bois étant disponible sur place ...",
budget:"Budget chaudière : 40 000€",
link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
{id:2,
  title:"EAU VYCHKOVO",
  image:"/Images/gravureLacLeman.webp",
  date:"novembre 2022",
  shortText:"Il s’agit de mettre en place une petite unité modulable et modulaire, facile d’utilisation dont la mise en place peut être rapide. Le procédé qui est proposé est agrée par les organisations internationales qui apportent leur soutien aux populations réfugiées et déplacées (UNCHR, UNICEF, ONU, PNUE UNOPS.) et mise en œuvre dans de nombreux pays de par le monde.",
  budget:"Budget projet : 40 000€",
  link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
{id:3,
  title:"EAU DUBOVE",
  image:"/Images/gravureLacLeman.webp",
  date:"novembre 2022",
  shortText:"Objectif du projet : L’objectif du projet est de permettre l’accès à l’eau potable aux populations déplacées qui sont accueillies dans des anciens établissements hospitaliers (hôpitaux, sanatorium, établissement thermal). Cet objectif permettra de diminuer les risques sanitaires.",
  budget:"Coût du projet : 50 000 € ",
  link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
{id:4,
  title:"EAU VELYKYI BYTCHKIV",
  image:"/Images/gravureLacLeman.webp",
  date:"novembre 2022",
  shortText:"Au sein de la commune il y a 7 lieux de regroupement des personnes déplacées. Le plus grand nombre est hébergé dans un ancien bâtiment du campus du Lycée Velykyi Bytchkiv. Il s’agit s’un ancien orphelinat construit en 1962 et abandonné depuis quelques années et réhabilité pour faire face aux demandes du Gouvernement de recevoir des populations déplacées. Aujourd’hui il y a 180 déplacés, essentiellement des femmes et des enfants qui sont logés précairement dans ce bâtiment. Ce bâtiment a été en partie réhabilité pour moitié, sa capacité totale initiale était de 450 élèves. ",
  budget:"Coût du projet : 30 000 € ",
  link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
{id:5,
  title:"Equipements « Grand Froid »",
  image:"/Images/gravureLacLeman.webp",
  date:"novembre 2022",
  shortText:"Cette terrible guerre en Ukraine n’a malheureusement pas cessé...L’hiver arrive et nos amis ukrainiens ont besoin de nous.Nous sommes sollicités par le centre de collecte humanitaire de Berditchev pour aider la population à affronter l’hiver glacial d’Ukraine auquel s’ajouté également le problématique des coupures électriques qui entrainent les coupures des générateurs de chauffage et des pompes de circulation ainsi que des radiateurs électriques.Vous trouvez ci-dessous une liste de besoins.Nous souhaitons leur venir en aide !",
  budget:"Coût du projet : 5 000 € ",
  link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
{id:6,
  title:"GROUPES ELECTROGENES",
  image:"/Images/gravureLacLeman.webp",
  date:"novembre 2022",
  shortText:"Nous sommes sollicités par notre réseau local d’aide humanitaire situé dans les régions de Transcarpatie, de Jitomir et de Kiev.Les frappes ciblées sur les infrastructures énergétiques privent de plus en plus les Ukrainiens de leurs besoins vitaux en électricité que ce soit dans les services d’urgence ou pour l’alimentation en eau, chauffage, nourriture etc...",
  budget:"OBJECTIF DU PROJET: 500 generateurs",
  link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
]