export const projects=[
{id:1,
title: "CHAUDIERE Ust-Chorna",
image:"/Images/gravureLacLeman.webp",
date:"novembre 2022",
shortText:"Il s’agit de mettre en place une nouvelle chaudière avant les mois d’hiver afin de permettre à tous les déplacés (actuels et futurs) d’être accueillis dans ces locaux et d’avoir accès à un chauffage et eau chaude.Le chauffage bois permettra à la communauté de réaliser des économies, le bois étant disponible sur place ...",
budget:"Budget chaudière : 40 000€",
tableTitle:"Equipements nécessaires pour l’organisation du chauffage dans le bâtiment de l’ancien hôpital d’Ust-Tchorna",
table: ' <div className="containerGrid"><div className="one num">N°</div><div className="one gridTitle">Titre</div><div className="one gridQuantity">Quantité</div><div className="one gridDimension">Dimension</div><div className="one gridPrice">Prix/UA</div><div className="one">1</div><div className="one gridTitle">Chaudière ALTER TRIO UNI</div><div className="one gridQuantity"></div><div className="one gridDimension">300 kW</div><div className="one gridPrice">275 000</div><div className="one">2</div><div className="one gridTitle">Pompe Grundfos</div><div className="one gridQuantity">2 unités</div><div className="one gridDimension">32/70</div><div className="one gridPrice">12 400</div><div className="one">3</div><div className="one gridTitle">Pompe Grundfos</div><div className="one gridQuantity">2 unités</div><div className="one gridDimension">32/80</div><div className="one gridPrice">28 000</div><div className="one">4</div><div className="one gridTitle">Pompe Grundfos</div><div className="one gridQuantity">2 unités</div><div className="one gridDimension">32/100</div><div className="one gridPrice">33 000</div><div className="one">5</div><div className="one gridTitle">Pompe Grundfos</div><div className="one gridQuantity">1 unité</div><div className="one gridDimension">40/150</div><div className="one gridPrice">54 000</div><div className="one">6</div><div className="one gridTitle">Réservoir</div><div className="one gridQuantity"></div><div className="one gridDimension">3 tonnes</div><div className="one gridPrice">30 000</div><div className="one">7</div><div className="one gridTitle">Réservoir tampon</div><div className="one gridQuantity">2 unités</div><div className="one gridDimension">100 liltres </div><div className="one gridPrice">7 000</div><div className="one">8</div><div className="one gridTitle">Mélangeur ESBE </div><div className="one gridQuantity"></div><div className="one gridDimension">2 pouces 50°</div><div className="one gridPrice">4 500</div><div className="one">9</div><div className="one gridTitle">Tube carré</div><div className="one gridQuantity"></div><div className="one gridDimension">200*200,  2 m</div><div className="one gridPrice">1 800</div><div className="one">10</div><div className="one gridTitle">Tube rond </div><div className="one gridQuantity"></div><div className="one gridDimension">Diamètre 80, 6 m</div><div className="one gridPrice">3 500</div><div className="one">11</div><div className="one gridTitle">Radiateurs </div><div className="one gridQuantity">80 unités</div><div className="one gridDimension">1,5 m chacun</div><div className="one gridPrice">328 000</div><div className="one">12</div><div className="one gridTitle">Kit des accessoires de gestion du radiateur (deux vannes en amont et en aval du radiateur et une vanne thermostatique)</div><div className="one gridQuantity">80 unités</div><div className="one gridDimension"></div><div className="one gridPrice">56 000</div><div className="one">13</div><div className="one gridTitle">Tube polypropylène</div><div className="one gridQuantity"></div><div className="one gridDimension">Diamètre 32, 800 m</div><div className="one gridPrice">80 000</div><div className="one">14</div><div className="one gridTitle">Tube polypropylène</div><div className="one gridQuantity"></div><div className="one gridDimension">Diamètre 20, 80 m</div><div className="one gridPrice">4 000</div><div className="one">15</div><div className="one gridTitle">Colliers de fixation du tube</div><div className="one gridQuantity">600 unités</div><div className="one gridDimension"></div><div className="one gridPrice">5 750</div><div className="one">16</div><div className="one gridTitle">Colliers de fixation du radiateur</div><div className="one gridQuantity">80 unités</div><div className="one gridDimension"></div><div className="one gridPrice">7 200</div><div className="one">17</div><div className="one gridTitle">Té bicône </div><div className="one gridQuantity">160 unités</div><div className="one gridDimension">32/20</div><div className="one gridPrice">4 900</div><div className="one">18</div><div className="one gridTitle">Coude</div><div className="one gridQuantity">160 unités</div><div className="one gridDimension"></div><div className="one gridPrice">4 500</div><div className="one">19</div><div className="one gridTitle">Vanne automatique</div><div className="one gridQuantity">3 unités  </div><div className="one gridDimension">0,5 pouce</div><div className="one gridPrice">1000</div><div className="one">20</div><div className="one gridTitle">Cheminé (sandwich) en kit</div><div className="one gridQuantity"></div><div className="one gridDimension"></div><div className="one gridPrice">58 000</div><div className="one">21</div><div className="one gridTitle">Montage du cheminé, montage et raccordement de la chaudière, soudage des réservoirs-tampons, montage et raccordement du réservoir, électrodes, peinture, filasse, ronds, etc.</div><div className="one gridQuantity"></div><div className="one gridDimension"></div><div className="one gridPrice">55 000</div><div className="one">22</div><div className="one gridTitle">Montage des radiateurs </div><div className="one gridQuantity">80 unités</div><div className="one gridDimension"></div><div className="one gridPrice">98 400</div><div className="one">2</div><div className="one gridTitle">TOTAL</div><div className="one gridQuantity">1</div><div className="one gridDimension">1</div><div className="one gridPrice">1 151 950 UAH</div><div className="one "></div><div className="one gridTitle">EQUIVALENT EUR</div><div className="one gridQuantity">1</div><div className="one gridDimension">1</div><div className="one gridPrice">30 500 euros</div><div className="one "></div><div className="one gridTitle">Frais de logistique </div><div className="one gridQuantity">/ administratif </div><div className="one gridDimension">/ installation environ </div><div className="one gridPrice">10 000 euros</div></div> '
},
{id:2,
  title:"EAU VYCHKOVO",
  image:"/Images/gravureLacLeman.webp",
  date:"novembre 2022",
  shortText:"Il s’agit de mettre en place une petite unité modulable et modulaire, facile d’utilisation dont la mise en place peut être rapide. Le procédé qui est proposé est agrée par les organisations internationales qui apportent leur soutien aux populations réfugiées et déplacées (UNCHR, UNICEF, ONU, PNUE UNOPS.) et mise en œuvre dans de nombreux pays de par le monde.",
  budget:"Budget projet : 40 000€",
  link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
{id:3,
  title:"EAU DUBOVE",
  image:"/Images/gravureLacLeman.webp",
  date:"novembre 2022",
  shortText:"Objectif du projet : L’objectif du projet est de permettre l’accès à l’eau potable aux populations déplacées qui sont accueillies dans des anciens établissements hospitaliers (hôpitaux, sanatorium, établissement thermal). Cet objectif permettra de diminuer les risques sanitaires.",
  budget:"Coût du projet : 50 000 € ",
  link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
{id:4,
  title:"EAU VELYKYI BYTCHKIV",
  image:"/Images/gravureLacLeman.webp",
  date:"novembre 2022",
  shortText:"Au sein de la commune il y a 7 lieux de regroupement des personnes déplacées. Le plus grand nombre est hébergé dans un ancien bâtiment du campus du Lycée Velykyi Bytchkiv. Il s’agit s’un ancien orphelinat construit en 1962 et abandonné depuis quelques années et réhabilité pour faire face aux demandes du Gouvernement de recevoir des populations déplacées. Aujourd’hui il y a 180 déplacés, essentiellement des femmes et des enfants qui sont logés précairement dans ce bâtiment. Ce bâtiment a été en partie réhabilité pour moitié, sa capacité totale initiale était de 450 élèves. ",
  budget:"Coût du projet : 30 000 € ",
  link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
{id:5,
  title:"Equipements « Grand Froid »",
  image:"/Images/gravureLacLeman.webp",
  date:"novembre 2022",
  shortText:"Cette terrible guerre en Ukraine n’a malheureusement pas cessé...L’hiver arrive et nos amis ukrainiens ont besoin de nous.Nous sommes sollicités par le centre de collecte humanitaire de Berditchev pour aider la population à affronter l’hiver glacial d’Ukraine auquel s’ajouté également le problématique des coupures électriques qui entrainent les coupures des générateurs de chauffage et des pompes de circulation ainsi que des radiateurs électriques.Vous trouvez ci-dessous une liste de besoins.Nous souhaitons leur venir en aide !",
  budget:"Coût du projet : 5 000 € ",
  link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
{id:6,
  title:"GROUPES ELECTROGENES",
  image:"/Images/gravureLacLeman.webp",
  date:"novembre 2022",
  shortText:"Nous sommes sollicités par notre réseau local d’aide humanitaire situé dans les régions de Transcarpatie, de Jitomir et de Kiev.Les frappes ciblées sur les infrastructures énergétiques privent de plus en plus les Ukrainiens de leurs besoins vitaux en électricité que ce soit dans les services d’urgence ou pour l’alimentation en eau, chauffage, nourriture etc...",
  budget:"OBJECTIF DU PROJET: 500 generateurs",
  link:"Il vous suffit de cliquer sur le lien ci-dessous et de vous laisser guider.https://www.helloasso.com/associations/association-franco-ukrainienne-balzac-et-hanska/formulaires/1. L’Association Franco Ukrainienne BALZAC HANSKA est une Association loi de 1901 N° W941007660 – ouvrant droit à une réduction d’impôt et délivrance d’un certificat de déductibilité fiscale.",
},
]
export const getObject = (array) =>
    array.reduce(
        (obj, article) => ({
            ...obj,
            [article.id]: article,
        }),
        {}
    )